//! Embedded SPIR-V for the Vulkan compositor pipelines.
//!
//! Regenerate after editing a GLSL source below with:
//! `glslc -O -fshader-stage=<stage> source.glsl -o shader.spv`.

const std = @import("std");

pub const quad_source =
    \\#version 450
    \\layout(push_constant) uniform Push {
    \\    vec2 target_size;
    \\    vec2 texture_size;
    \\    float swap_rb;
    \\} pc;
    \\layout(location=0) in vec4 in_dest;
    \\layout(location=1) in vec4 in_source;
    \\layout(location=2) in vec4 in_clip;
    \\layout(location=3) in vec4 in_color;
    \\layout(location=4) in vec4 in_rounded;
    \\layout(location=5) in vec4 in_parameters;
    \\layout(location=0) out vec2 pixel;
    \\layout(location=1) flat out vec4 dest;
    \\layout(location=2) flat out vec4 source;
    \\layout(location=3) flat out vec4 color;
    \\layout(location=4) flat out vec4 rounded;
    \\layout(location=5) flat out vec4 parameters;
    \\void main() {
    \\    vec2 q=vec2(float(gl_VertexIndex&1),float((gl_VertexIndex>>1)&1));
    \\    vec2 pos=in_clip.xy+q*in_clip.zw;
    \\    gl_Position=vec4(pos/pc.target_size*2.0-1.0,0,1);
    \\    pixel=pos;
    \\    dest=in_dest;
    \\    source=in_source;
    \\    color=in_color;
    \\    rounded=in_rounded;
    \\    parameters=in_parameters;
    \\}
;

pub const solid_source =
    \\#version 450
    \\layout(push_constant) uniform Push {
    \\    vec2 target_size;
    \\    vec2 texture_size;
    \\    float swap_rb;
    \\} pc;
    \\layout(location=3) flat in vec4 color;
    \\layout(location=0) out vec4 out_color;
    \\void main() { out_color=pc.swap_rb>0.5 ? color.bgra : color; }
;

pub const image_source =
    \\#version 450
    \\layout(set=0,binding=0) uniform sampler2D tex;
    \\layout(push_constant) uniform Push {
    \\    vec2 target_size;
    \\    vec2 texture_size;
    \\    float swap_rb;
    \\} pc;
    \\layout(location=0) in vec2 pixel;
    \\layout(location=1) flat in vec4 dest;
    \\layout(location=2) flat in vec4 source;
    \\layout(location=4) flat in vec4 rounded;
    \\layout(location=5) flat in vec4 parameters;
    \\layout(location=0) out vec4 out_color;
    \\void main() {
    \\    vec2 q=(pixel-dest.xy)/dest.zw;
    \\    vec2 uv=(source.xy+q*source.zw)/pc.texture_size;
    \\    vec4 color=texture(tex,uv);
    \\    if (pc.swap_rb>0.5) color=color.bgra;
    \\    if (parameters.x>0.0) {
    \\        vec2 center=clamp(pixel,rounded.xy+vec2(parameters.x),rounded.xy+rounded.zw-vec2(parameters.x));
    \\        float coverage=clamp(parameters.x+0.5-distance(pixel,center),0.0,1.0);
    \\        color*=coverage;
    \\    }
    \\    out_color=pc.swap_rb>0.5 ? color.bgra : color;
    \\}
;

pub const shadow_source =
    \\#version 450
    \\layout(push_constant) uniform Push {
    \\    vec2 target_size;
    \\    vec2 texture_size;
    \\    float swap_rb;
    \\} pc;
    \\layout(location=0) in vec2 pixel;
    \\layout(location=3) flat in vec4 color;
    \\layout(location=4) flat in vec4 rounded;
    \\layout(location=5) flat in vec4 parameters;
    \\layout(location=0) out vec4 out_color;
    \\void main() {
    \\    vec2 q=abs(pixel-(rounded.xy+rounded.zw*0.5))-(rounded.zw*0.5-vec2(parameters.x));
    \\    float distance=length(max(q,vec2(0)))+min(max(q.x,q.y),0.0)-parameters.x;
    \\    float coverage=parameters.y>0.0 ? clamp(0.5-distance/(2.0*parameters.y),0.0,1.0) : clamp(0.5-distance,0.0,1.0);
    \\    vec4 shaded=color*coverage;
    \\    out_color=pc.swap_rb>0.5 ? shaded.bgra : shaded;
    \\}
;

pub const blur_horizontal_paired_source =
    \\#version 450
    \\layout(set=0,binding=0) uniform sampler2D tex;
    \\layout(push_constant) uniform Push {
    \\    vec2 target_size;
    \\    vec2 texture_size;
    \\    float swap_rb;
    \\} pc;
    \\layout(location=0) in vec2 pixel;
    \\layout(location=5) flat in vec4 parameters;
    \\layout(location=0) out vec4 out_color;
    \\void main() {
    \\    ivec2 coordinate=ivec2(pixel);
    \\    int radius=int(parameters.x);
    \\    int left=min(radius,coordinate.x);
    \\    int right=min(radius,int(pc.texture_size.x)-1-coordinate.x);
    \\    vec2 center=(vec2(coordinate)+vec2(0.5))/pc.texture_size;
    \\    vec4 sum=texelFetch(tex,coordinate,0);
    \\    for (int offset=1; offset<=left; offset+=2) {
    \\        if (offset<left) {
    \\            sum+=2.0*texture(tex,center-vec2(float(offset)+0.5,0.0)/pc.texture_size);
    \\        } else {
    \\            sum+=texelFetch(tex,coordinate-ivec2(offset,0),0);
    \\        }
    \\    }
    \\    for (int offset=1; offset<=right; offset+=2) {
    \\        if (offset<right) {
    \\            sum+=2.0*texture(tex,center+vec2(float(offset)+0.5,0.0)/pc.texture_size);
    \\        } else {
    \\            sum+=texelFetch(tex,coordinate+ivec2(offset,0),0);
    \\        }
    \\    }
    \\    out_color=sum/float(1+left+right);
    \\}
;

pub const blur_vertical_paired_source =
    \\#version 450
    \\layout(set=0,binding=0) uniform sampler2D tex;
    \\layout(push_constant) uniform Push {
    \\    vec2 target_size;
    \\    vec2 texture_size;
    \\    float swap_rb;
    \\} pc;
    \\layout(location=0) in vec2 pixel;
    \\layout(location=5) flat in vec4 parameters;
    \\layout(location=0) out vec4 out_color;
    \\void main() {
    \\    ivec2 coordinate=ivec2(pixel);
    \\    int radius=int(parameters.x);
    \\    int top=min(radius,coordinate.y);
    \\    int bottom=min(radius,int(pc.texture_size.y)-1-coordinate.y);
    \\    vec2 center=(vec2(coordinate)+vec2(0.5))/pc.texture_size;
    \\    vec4 sum=texelFetch(tex,coordinate,0);
    \\    for (int offset=1; offset<=top; offset+=2) {
    \\        if (offset<top) {
    \\            sum+=2.0*texture(tex,center-vec2(0.0,float(offset)+0.5)/pc.texture_size);
    \\        } else {
    \\            sum+=texelFetch(tex,coordinate-ivec2(0,offset),0);
    \\        }
    \\    }
    \\    for (int offset=1; offset<=bottom; offset+=2) {
    \\        if (offset<bottom) {
    \\            sum+=2.0*texture(tex,center+vec2(0.0,float(offset)+0.5)/pc.texture_size);
    \\        } else {
    \\            sum+=texelFetch(tex,coordinate+ivec2(0,offset),0);
    \\        }
    \\    }
    \\    out_color=sum/float(1+top+bottom);
    \\}
;

pub const quad = decodeSpirv(
    "AwIjBwAAAQALAA0ATwAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ACQAAAAAABAAA" ++
        "AG1haW4AAAAADAAAACsAAAA+AAAATAAAAEcABAAMAAAACwAAACoAAABHAAMAGAAAAAIAAABIAAUAGAAAAAAAAAAjAAAAAAAAAEgA" ++
        "BQAYAAAAAQAAACMAAAAQAAAASAAFABgAAAACAAAAIwAAACAAAABIAAUAGAAAAAMAAAAjAAAAKAAAAEgABQAYAAAABAAAACMAAAAw" ++
        "AAAASAAFABgAAAAFAAAAIwAAAEAAAABIAAUAGAAAAAYAAAAjAAAAUAAAAEgABQAYAAAABwAAACMAAABUAAAASAAFABgAAAAIAAAA" ++
        "IwAAAFgAAABHAAMAKQAAAAIAAABIAAUAKQAAAAAAAAALAAAAAAAAAEgABQApAAAAAQAAAAsAAAABAAAASAAFACkAAAACAAAACwAA" ++
        "AAMAAABIAAUAKQAAAAMAAAALAAAABAAAAEcABAA+AAAAHgAAAAAAAABHAAQATAAAAB4AAAABAAAAEwACAAIAAAAhAAMAAwAAAAIA" ++
        "AAAWAAMABgAAACAAAAAXAAQABwAAAAYAAAACAAAAFQAEAAoAAAAgAAAAAQAAACAABAALAAAAAQAAAAoAAAA7AAQACwAAAAwAAAAB" ++
        "AAAAKwAEAAoAAAAOAAAAAQAAABcABAAXAAAABgAAAAQAAAAeAAsAGAAAABcAAAAXAAAABwAAAAcAAAAXAAAAFwAAAAYAAAAGAAAA" ++
        "BgAAACAABAAZAAAACQAAABgAAAA7AAQAGQAAABoAAAAJAAAAKwAEAAoAAAAbAAAAAAAAACAABAAcAAAACQAAABcAAAAVAAQAJgAA" ++
        "ACAAAAAAAAAAKwAEACYAAAAnAAAAAQAAABwABAAoAAAABgAAACcAAAAeAAYAKQAAABcAAAAGAAAAKAAAACgAAAAgAAQAKgAAAAMA" ++
        "AAApAAAAOwAEACoAAAArAAAAAwAAACsABAAKAAAALQAAAAIAAAAgAAQALgAAAAkAAAAHAAAAKwAEAAYAAAAyAAAAAAAAQCsABAAG" ++
        "AAAANAAAAAAAgD8rAAQABgAAADcAAAAAAAAAIAAEADsAAAADAAAAFwAAACAABAA9AAAAAwAAAAcAAAA7AAQAPQAAAD4AAAADAAAA" ++
        "KwAEAAoAAABIAAAAAwAAADsABAA9AAAATAAAAAMAAAAsAAUABwAAAE4AAAA0AAAANAAAADYABQACAAAABAAAAAAAAAADAAAA+AAC" ++
        "AAUAAAA9AAQACgAAAA0AAAAMAAAAxwAFAAoAAAAPAAAADQAAAA4AAABvAAQABgAAABAAAAAPAAAAwwAFAAoAAAASAAAADQAAAA4A" ++
        "AADHAAUACgAAABMAAAASAAAADgAAAG8ABAAGAAAAFAAAABMAAABQAAUABwAAABUAAAAQAAAAFAAAAEEABQAcAAAAHQAAABoAAAAb" ++
        "AAAAPQAEABcAAAAeAAAAHQAAAE8ABwAHAAAAHwAAAB4AAAAeAAAAAAAAAAEAAABPAAcABwAAACMAAAAeAAAAHgAAAAIAAAADAAAA" ++
        "hQAFAAcAAAAkAAAAFQAAACMAAACBAAUABwAAACUAAAAfAAAAJAAAAEEABQAuAAAALwAAABoAAAAtAAAAPQAEAAcAAAAwAAAALwAA" ++
        "AIgABQAHAAAAMQAAACUAAAAwAAAAjgAFAAcAAAAzAAAAMQAAADIAAACDAAUABwAAADYAAAAzAAAATgAAAFEABQAGAAAAOAAAADYA" ++
        "AAAAAAAAUQAFAAYAAAA5AAAANgAAAAEAAABQAAcAFwAAADoAAAA4AAAAOQAAADcAAAA0AAAAQQAFADsAAAA8AAAAKwAAABsAAAA+" ++
        "AAMAPAAAADoAAABBAAUAHAAAAD8AAAAaAAAADgAAAD0ABAAXAAAAQAAAAD8AAABPAAcABwAAAEEAAABAAAAAQAAAAAAAAAABAAAA" ++
        "TwAHAAcAAABFAAAAQAAAAEAAAAACAAAAAwAAAIUABQAHAAAARgAAABUAAABFAAAAgQAFAAcAAABHAAAAQQAAAEYAAABBAAUALgAA" ++
        "AEkAAAAaAAAASAAAAD0ABAAHAAAASgAAAEkAAACIAAUABwAAAEsAAABHAAAASgAAAD4AAwA+AAAASwAAAD4AAwBMAAAAJQAAAP0A" ++
        "AQA4AAEA",
);

pub const solid = decodeSpirv(
    "AwIjBwAAAQALAA0AJAAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ABgAEAAAABAAA" ++
        "AG1haW4AAAAACQAAABAAAwAEAAAABwAAAEcABAAJAAAAHgAAAAAAAABHAAMACwAAAAIAAABIAAUACwAAAAAAAAAjAAAAAAAAAEgA" ++
        "BQALAAAAAQAAACMAAAAQAAAASAAFAAsAAAACAAAAIwAAACAAAABIAAUACwAAAAMAAAAjAAAAKAAAAEgABQALAAAABAAAACMAAAAw" ++
        "AAAASAAFAAsAAAAFAAAAIwAAAEAAAABIAAUACwAAAAYAAAAjAAAAUAAAAEgABQALAAAABwAAACMAAABUAAAASAAFAAsAAAAIAAAA" ++
        "IwAAAFgAAAATAAIAAgAAACEAAwADAAAAAgAAABYAAwAGAAAAIAAAABcABAAHAAAABgAAAAQAAAAgAAQACAAAAAMAAAAHAAAAOwAE" ++
        "AAgAAAAJAAAAAwAAABcABAAKAAAABgAAAAIAAAAeAAsACwAAAAcAAAAHAAAACgAAAAoAAAAHAAAABwAAAAYAAAAGAAAABgAAACAA" ++
        "BAAMAAAACQAAAAsAAAA7AAQADAAAAA0AAAAJAAAAFQAEAA4AAAAgAAAAAQAAACsABAAOAAAADwAAAAgAAAAgAAQAEAAAAAkAAAAG" ++
        "AAAAKwAEAAYAAAATAAAAAAAAPxQAAgAUAAAAKwAEAA4AAAAaAAAABAAAACAABAAbAAAACQAAAAcAAAA2AAUAAgAAAAQAAAAAAAAA" ++
        "AwAAAPgAAgAFAAAAQQAFABAAAAARAAAADQAAAA8AAAA9AAQABgAAABIAAAARAAAAugAFABQAAAAVAAAAEgAAABMAAAD3AAMAGQAA" ++
        "AAAAAAD6AAQAFQAAABgAAAAfAAAA+AACABgAAABBAAUAGwAAABwAAAANAAAAGgAAAD0ABAAHAAAAHQAAABwAAABPAAkABwAAAB4A" ++
        "AAAdAAAAHQAAAAIAAAABAAAAAAAAAAMAAAD5AAIAGQAAAPgAAgAfAAAAQQAFABsAAAAgAAAADQAAABoAAAA9AAQABwAAACEAAAAg" ++
        "AAAA+QACABkAAAD4AAIAGQAAAPUABwAHAAAAIwAAAB4AAAAYAAAAIQAAAB8AAAA+AAMACQAAACMAAAD9AAEAOAABAA==",
);

pub const image = decodeSpirv(
    "AwIjBwAAAQALAA0AYQAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ACAAEAAAABAAA" ++
        "AG1haW4AAAAAEQAAACwAAABSAAAAEAADAAQAAAAHAAAARwAEAA0AAAAhAAAAAAAAAEcABAANAAAAIgAAAAAAAABHAAQAEQAAAB4A" ++
        "AAAAAAAARwADABQAAAACAAAASAAFABQAAAAAAAAAIwAAAAAAAABIAAUAFAAAAAEAAAAjAAAAEAAAAEgABQAUAAAAAgAAACMAAAAg" ++
        "AAAASAAFABQAAAADAAAAIwAAACgAAABIAAUAFAAAAAQAAAAjAAAAMAAAAEgABQAUAAAABQAAACMAAABAAAAASAAFABQAAAAGAAAA" ++
        "IwAAAFAAAABIAAUAFAAAAAcAAAAjAAAAVAAAAEgABQAUAAAACAAAACMAAABYAAAARwAEACwAAAAeAAAAAQAAAEcABABSAAAAHgAA" ++
        "AAAAAAATAAIAAgAAACEAAwADAAAAAgAAABYAAwAGAAAAIAAAABcABAAHAAAABgAAAAQAAAAZAAkACgAAAAYAAAABAAAAAAAAAAAA" ++
        "AAAAAAAAAQAAAAAAAAAbAAMACwAAAAoAAAAgAAQADAAAAAAAAAALAAAAOwAEAAwAAAANAAAAAAAAABcABAAPAAAABgAAAAIAAAAg" ++
        "AAQAEAAAAAEAAAAPAAAAOwAEABAAAAARAAAAAQAAAB4ACwAUAAAABwAAAAcAAAAPAAAADwAAAAcAAAAHAAAABgAAAAYAAAAGAAAA" ++
        "IAAEABUAAAAJAAAAFAAAADsABAAVAAAAFgAAAAkAAAAVAAQAFwAAACAAAAABAAAAKwAEABcAAAAYAAAACAAAACAABAAZAAAACQAA" ++
        "AAYAAAArAAQABgAAABwAAAAAAAA/FAACAB0AAAArAAQAFwAAACMAAAAGAAAAKwAEAAYAAAAmAAAAAAAAADsABAAQAAAALAAAAAEA" ++
        "AAArAAQAFwAAAC4AAAAFAAAAIAAEAC8AAAAJAAAABwAAACsABAAGAAAATAAAAAAAgD8gAAQAUQAAAAMAAAAHAAAAOwAEAFEAAABS" ++
        "AAAAAwAAADYABQACAAAABAAAAAAAAAADAAAA+AACAAUAAAA9AAQACwAAAA4AAAANAAAAPQAEAA8AAAASAAAAEQAAAFcABQAHAAAA" ++
        "EwAAAA4AAAASAAAAQQAFABkAAAAaAAAAFgAAABgAAAA9AAQABgAAABsAAAAaAAAAugAFAB0AAAAeAAAAGwAAABwAAAD3AAMAIAAA" ++
        "AAAAAAD6AAQAHgAAAB8AAAAgAAAA+AACAB8AAABPAAkABwAAACIAAAATAAAAEwAAAAIAAAABAAAAAAAAAAMAAAD5AAIAIAAAAPgA" ++
        "AgAgAAAA9QAHAAcAAABeAAAAEwAAAAUAAAAiAAAAHwAAAEEABQAZAAAAJAAAABYAAAAjAAAAPQAEAAYAAAAlAAAAJAAAALoABQAd" ++
        "AAAAJwAAACUAAAAmAAAA9wADACkAAAAAAAAA+gAEACcAAAAoAAAAKQAAAPgAAgAoAAAAPQAEAA8AAAAtAAAALAAAAEEABQAvAAAA" ++
        "MAAAABYAAAAuAAAAPQAEAAcAAAAxAAAAMAAAAE8ABwAPAAAAMgAAADEAAAAxAAAAAAAAAAEAAABQAAUADwAAADUAAAAlAAAAJQAA" ++
        "AIEABQAPAAAANgAAADIAAAA1AAAATwAHAA8AAAA8AAAAMQAAADEAAAACAAAAAwAAAIEABQAPAAAAPQAAADIAAAA8AAAAgwAFAA8A" ++
        "AABBAAAAPQAAADUAAAAMAAgADwAAAEIAAAABAAAAKwAAAC0AAAA2AAAAQQAAAIEABQAGAAAARwAAACUAAAAcAAAADAAHAAYAAABK" ++
        "AAAAAQAAAEMAAAAtAAAAQgAAAIMABQAGAAAASwAAAEcAAABKAAAADAAIAAYAAABNAAAAAQAAACsAAABLAAAAJgAAAEwAAACOAAUA" ++
        "BwAAAFAAAABeAAAATQAAAPkAAgApAAAA+AACACkAAAD1AAcABwAAAF8AAABeAAAAIAAAAFAAAAAoAAAA9wADAFgAAAAAAAAA+gAE" ++
        "AB4AAABXAAAAWwAAAPgAAgBXAAAATwAJAAcAAABaAAAAXwAAAF8AAAACAAAAAQAAAAAAAAADAAAA+QACAFgAAAD4AAIAWwAAAPkA" ++
        "AgBYAAAA+AACAFgAAAD1AAcABwAAAGAAAABaAAAAVwAAAF8AAABbAAAAPgADAFIAAABgAAAA/QABADgAAQA=",
);

pub const shadow = decodeSpirv(
    "AwIjBwAAAQALAA0AbgAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ABwAEAAAABAAA" ++
        "AG1haW4AAAAACwAAAF0AAAAQAAMABAAAAAcAAABHAAQACwAAAB4AAAABAAAARwADAA4AAAACAAAASAAFAA4AAAAAAAAAIwAAAAAA" ++
        "AABIAAUADgAAAAEAAAAjAAAAEAAAAEgABQAOAAAAAgAAACMAAAAgAAAASAAFAA4AAAADAAAAIwAAACgAAABIAAUADgAAAAQAAAAj" ++
        "AAAAMAAAAEgABQAOAAAABQAAACMAAABAAAAASAAFAA4AAAAGAAAAIwAAAFAAAABIAAUADgAAAAcAAAAjAAAAVAAAAEgABQAOAAAA" ++
        "CAAAACMAAABYAAAARwAEAF0AAAAeAAAAAAAAABMAAgACAAAAIQADAAMAAAACAAAAFgADAAYAAAAgAAAAFwAEAAcAAAAGAAAAAgAA" ++
        "ACAABAAKAAAAAQAAAAcAAAA7AAQACgAAAAsAAAABAAAAFwAEAA0AAAAGAAAABAAAAB4ACwAOAAAADQAAAA0AAAAHAAAABwAAAA0A" ++
        "AAANAAAABgAAAAYAAAAGAAAAIAAEAA8AAAAJAAAADgAAADsABAAPAAAAEAAAAAkAAAAVAAQAEQAAACAAAAABAAAAKwAEABEAAAAS" ++
        "AAAABQAAACAABAATAAAACQAAAA0AAAArAAQABgAAABoAAAAAAAA/KwAEABEAAAAjAAAABgAAACAABAAkAAAACQAAAAYAAAArAAQA" ++
        "BgAAAC0AAAAAAAAALAAFAAcAAAAuAAAALQAAAC0AAAArAAQAEQAAAD8AAAAHAAAAFAACAEIAAAArAAQABgAAAEgAAAAAAABAKwAE" ++
        "AAYAAABOAAAAAACAPysABAARAAAAVwAAAAQAAAAgAAQAXAAAAAMAAAANAAAAOwAEAFwAAABdAAAAAwAAACsABAARAAAAXgAAAAgA" ++
        "AAA2AAUAAgAAAAQAAAAAAAAAAwAAAPgAAgAFAAAAPQAEAAcAAAAMAAAACwAAAEEABQATAAAAFAAAABAAAAASAAAAPQAEAA0AAAAV" ++
        "AAAAFAAAAE8ABwAHAAAAFgAAABUAAAAVAAAAAAAAAAEAAABPAAcABwAAABkAAAAVAAAAFQAAAAIAAAADAAAAjgAFAAcAAAAbAAAA" ++
        "GQAAABoAAACBAAUABwAAABwAAAAWAAAAGwAAAIMABQAHAAAAHQAAAAwAAAAcAAAADAAGAAcAAAAeAAAAAQAAAAQAAAAdAAAAQQAF" ++
        "ACQAAAAlAAAAEAAAACMAAAA9AAQABgAAACYAAAAlAAAAUAAFAAcAAAAnAAAAJgAAACYAAACDAAUABwAAACgAAAAbAAAAJwAAAIMA" ++
        "BQAHAAAAKQAAAB4AAAAoAAAADAAHAAcAAAAvAAAAAQAAACgAAAApAAAALgAAAAwABgAGAAAAMAAAAAEAAABCAAAALwAAAFEABQAG" ++
        "AAAANAAAACkAAAAAAAAAUQAFAAYAAAA3AAAAKQAAAAEAAAAMAAcABgAAADgAAAABAAAAKAAAADQAAAA3AAAADAAHAAYAAAA5AAAA" ++
        "AQAAACUAAAA4AAAALQAAAIEABQAGAAAAOgAAADAAAAA5AAAAgwAFAAYAAAA9AAAAOgAAACYAAABBAAUAJAAAAEAAAAAQAAAAPwAA" ++
        "AD0ABAAGAAAAQQAAAEAAAAC6AAUAQgAAAEMAAABBAAAALQAAAPcAAwBGAAAAAAAAAPoABABDAAAARQAAAFAAAAD4AAIARQAAAIUA" ++
        "BQAGAAAASwAAAEgAAABBAAAAiAAFAAYAAABMAAAAPQAAAEsAAACDAAUABgAAAE0AAAAaAAAATAAAAAwACAAGAAAATwAAAAEAAAAr" ++
        "AAAATQAAAC0AAABOAAAA+QACAEYAAAD4AAIAUAAAAIMABQAGAAAAUgAAABoAAAA9AAAADAAIAAYAAABTAAAAAQAAACsAAABSAAAA" ++
        "LQAAAE4AAAD5AAIARgAAAPgAAgBGAAAA9QAHAAYAAABsAAAATwAAAEUAAABTAAAAUAAAAEEABQATAAAAWAAAABAAAABXAAAAPQAE" ++
        "AA0AAABZAAAAWAAAAI4ABQANAAAAWwAAAFkAAABsAAAAQQAFACQAAABfAAAAEAAAAF4AAAA9AAQABgAAAGAAAABfAAAAugAFAEIA" ++
        "AABhAAAAYAAAABoAAAD3AAMAZAAAAAAAAAD6AAQAYQAAAGMAAABnAAAA+AACAGMAAABPAAkADQAAAGYAAABbAAAAWwAAAAIAAAAB" ++
        "AAAAAAAAAAMAAAD5AAIAZAAAAPgAAgBnAAAA+QACAGQAAAD4AAIAZAAAAPUABwANAAAAbQAAAGYAAABjAAAAWwAAAGcAAAA+AAMA" ++
        "XQAAAG0AAAD9AAEAOAABAA==",
);

pub const quad_instanced = decodeSpirv(
    "AwIjBwAAAQALAA0ATgAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8AEwAAAAAABAAA" ++
        "AG1haW4AAAAADAAAABkAAAAmAAAAPAAAAD4AAAA/AAAAQQAAAEIAAABEAAAARQAAAEcAAABIAAAASgAAAEsAAABHAAQADAAAAAsA" ++
        "AAAqAAAARwAEABkAAAAeAAAAAgAAAEcAAwAkAAAAAgAAAEgABQAkAAAAAAAAAAsAAAAAAAAASAAFACQAAAABAAAACwAAAAEAAABI" ++
        "AAUAJAAAAAIAAAALAAAAAwAAAEgABQAkAAAAAwAAAAsAAAAEAAAARwADACkAAAACAAAASAAFACkAAAAAAAAAIwAAAAAAAABIAAUA" ++
        "KQAAAAEAAAAjAAAACAAAAEgABQApAAAAAgAAACMAAAAQAAAARwAEADwAAAAeAAAAAAAAAEcAAwA+AAAADgAAAEcABAA+AAAAHgAA" ++
        "AAEAAABHAAQAPwAAAB4AAAAAAAAARwADAEEAAAAOAAAARwAEAEEAAAAeAAAAAgAAAEcABABCAAAAHgAAAAEAAABHAAMARAAAAA4A" ++
        "AABHAAQARAAAAB4AAAADAAAARwAEAEUAAAAeAAAAAwAAAEcAAwBHAAAADgAAAEcABABHAAAAHgAAAAQAAABHAAQASAAAAB4AAAAE" ++
        "AAAARwADAEoAAAAOAAAARwAEAEoAAAAeAAAABQAAAEcABABLAAAAHgAAAAUAAAATAAIAAgAAACEAAwADAAAAAgAAABYAAwAGAAAA" ++
        "IAAAABcABAAHAAAABgAAAAIAAAAVAAQACgAAACAAAAABAAAAIAAEAAsAAAABAAAACgAAADsABAALAAAADAAAAAEAAAArAAQACgAA" ++
        "AA4AAAABAAAAFwAEABcAAAAGAAAABAAAACAABAAYAAAAAQAAABcAAAA7AAQAGAAAABkAAAABAAAAFQAEACEAAAAgAAAAAAAAACsA" ++
        "BAAhAAAAIgAAAAEAAAAcAAQAIwAAAAYAAAAiAAAAHgAGACQAAAAXAAAABgAAACMAAAAjAAAAIAAEACUAAAADAAAAJAAAADsABAAl" ++
        "AAAAJgAAAAMAAAArAAQACgAAACcAAAAAAAAAHgAFACkAAAAHAAAABwAAAAYAAAAgAAQAKgAAAAkAAAApAAAAOwAEACoAAAArAAAA" ++
        "CQAAACAABAAsAAAACQAAAAcAAAArAAQABgAAADAAAAAAAABAKwAEAAYAAAAyAAAAAACAPysABAAGAAAANQAAAAAAAAAgAAQAOQAA" ++
        "AAMAAAAXAAAAIAAEADsAAAADAAAABwAAADsABAA7AAAAPAAAAAMAAAA7AAQAOQAAAD4AAAADAAAAOwAEABgAAAA/AAAAAQAAADsA" ++
        "BAA5AAAAQQAAAAMAAAA7AAQAGAAAAEIAAAABAAAAOwAEADkAAABEAAAAAwAAADsABAAYAAAARQAAAAEAAAA7AAQAOQAAAEcAAAAD" ++
        "AAAAOwAEABgAAABIAAAAAQAAADsABAA5AAAASgAAAAMAAAA7AAQAGAAAAEsAAAABAAAALAAFAAcAAABNAAAAMgAAADIAAAA2AAUA" ++
        "AgAAAAQAAAAAAAAAAwAAAPgAAgAFAAAAPQAEAAoAAAANAAAADAAAAMcABQAKAAAADwAAAA0AAAAOAAAAbwAEAAYAAAAQAAAADwAA" ++
        "AMMABQAKAAAAEgAAAA0AAAAOAAAAxwAFAAoAAAATAAAAEgAAAA4AAABvAAQABgAAABQAAAATAAAAUAAFAAcAAAAVAAAAEAAAABQA" ++
        "AAA9AAQAFwAAABoAAAAZAAAATwAHAAcAAAAbAAAAGgAAABoAAAAAAAAAAQAAAE8ABwAHAAAAHgAAABoAAAAaAAAAAgAAAAMAAACF" ++
        "AAUABwAAAB8AAAAVAAAAHgAAAIEABQAHAAAAIAAAABsAAAAfAAAAQQAFACwAAAAtAAAAKwAAACcAAAA9AAQABwAAAC4AAAAtAAAA" ++
        "iAAFAAcAAAAvAAAAIAAAAC4AAACOAAUABwAAADEAAAAvAAAAMAAAAIMABQAHAAAANAAAADEAAABNAAAAUQAFAAYAAAA2AAAANAAA" ++
        "AAAAAABRAAUABgAAADcAAAA0AAAAAQAAAFAABwAXAAAAOAAAADYAAAA3AAAANQAAADIAAABBAAUAOQAAADoAAAAmAAAAJwAAAD4A" ++
        "AwA6AAAAOAAAAD4AAwA8AAAAIAAAAD0ABAAXAAAAQAAAAD8AAAA+AAMAPgAAAEAAAAA9AAQAFwAAAEMAAABCAAAAPgADAEEAAABD" ++
        "AAAAPQAEABcAAABGAAAARQAAAD4AAwBEAAAARgAAAD0ABAAXAAAASQAAAEgAAAA+AAMARwAAAEkAAAA9AAQAFwAAAEwAAABLAAAA" ++
        "PgADAEoAAABMAAAA/QABADgAAQA=",
);

pub const solid_instanced = decodeSpirv(
    "AwIjBwAAAQALAA0AIgAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ABwAEAAAABAAA" ++
        "AG1haW4AAAAACQAAABsAAAAQAAMABAAAAAcAAABHAAQACQAAAB4AAAAAAAAARwADAAsAAAACAAAASAAFAAsAAAAAAAAAIwAAAAAA" ++
        "AABIAAUACwAAAAEAAAAjAAAACAAAAEgABQALAAAAAgAAACMAAAAQAAAARwADABsAAAAOAAAARwAEABsAAAAeAAAAAwAAABMAAgAC" ++
        "AAAAIQADAAMAAAACAAAAFgADAAYAAAAgAAAAFwAEAAcAAAAGAAAABAAAACAABAAIAAAAAwAAAAcAAAA7AAQACAAAAAkAAAADAAAA" ++
        "FwAEAAoAAAAGAAAAAgAAAB4ABQALAAAACgAAAAoAAAAGAAAAIAAEAAwAAAAJAAAACwAAADsABAAMAAAADQAAAAkAAAAVAAQADgAA" ++
        "ACAAAAABAAAAKwAEAA4AAAAPAAAAAgAAACAABAAQAAAACQAAAAYAAAArAAQABgAAABMAAAAAAAA/FAACABQAAAAgAAQAGgAAAAEA" ++
        "AAAHAAAAOwAEABoAAAAbAAAAAQAAADYABQACAAAABAAAAAAAAAADAAAA+AACAAUAAABBAAUAEAAAABEAAAANAAAADwAAAD0ABAAG" ++
        "AAAAEgAAABEAAAC6AAUAFAAAABUAAAASAAAAEwAAAPcAAwAZAAAAAAAAAPoABAAVAAAAGAAAAB4AAAD4AAIAGAAAAD0ABAAHAAAA" ++
        "HAAAABsAAABPAAkABwAAAB0AAAAcAAAAHAAAAAIAAAABAAAAAAAAAAMAAAD5AAIAGQAAAPgAAgAeAAAAPQAEAAcAAAAfAAAAGwAA" ++
        "APkAAgAZAAAA+AACABkAAAD1AAcABwAAACEAAAAdAAAAGAAAAB8AAAAeAAAAPgADAAkAAAAhAAAA/QABADgAAQA=",
);

pub const image_instanced = decodeSpirv(
    "AwIjBwAAAQALAA0AdwAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ACwAEAAAABAAA" ++
        "AG1haW4AAAAACwAAAA8AAAAXAAAAPAAAAEgAAABoAAAAEAADAAQAAAAHAAAARwAEAAsAAAAeAAAAAAAAAEcAAwAPAAAADgAAAEcA" ++
        "BAAPAAAAHgAAAAEAAABHAAMAFwAAAA4AAABHAAQAFwAAAB4AAAACAAAARwADAB8AAAACAAAASAAFAB8AAAAAAAAAIwAAAAAAAABI" ++
        "AAUAHwAAAAEAAAAjAAAACAAAAEgABQAfAAAAAgAAACMAAAAQAAAARwAEAC0AAAAhAAAAAAAAAEcABAAtAAAAIgAAAAAAAABHAAMA" ++
        "PAAAAA4AAABHAAQAPAAAAB4AAAAFAAAARwADAEgAAAAOAAAARwAEAEgAAAAeAAAABAAAAEcABABoAAAAHgAAAAAAAAATAAIAAgAA" ++
        "ACEAAwADAAAAAgAAABYAAwAGAAAAIAAAABcABAAHAAAABgAAAAIAAAAgAAQACgAAAAEAAAAHAAAAOwAEAAoAAAALAAAAAQAAABcA" ++
        "BAANAAAABgAAAAQAAAAgAAQADgAAAAEAAAANAAAAOwAEAA4AAAAPAAAAAQAAADsABAAOAAAAFwAAAAEAAAAeAAUAHwAAAAcAAAAH" ++
        "AAAABgAAACAABAAgAAAACQAAAB8AAAA7AAQAIAAAACEAAAAJAAAAFQAEACIAAAAgAAAAAQAAACsABAAiAAAAIwAAAAEAAAAgAAQA" ++
        "JAAAAAkAAAAHAAAAGQAJACoAAAAGAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAGwADACsAAAAqAAAAIAAEACwAAAAAAAAAKwAA" ++
        "ADsABAAsAAAALQAAAAAAAAArAAQAIgAAADEAAAACAAAAIAAEADIAAAAJAAAABgAAACsABAAGAAAANQAAAAAAAD8UAAIANgAAADsA" ++
        "BAAOAAAAPAAAAAEAAAAVAAQAPQAAACAAAAAAAAAAKwAEAD0AAAA+AAAAAAAAACAABAA/AAAAAQAAAAYAAAArAAQABgAAAEIAAAAA" ++
        "AAAAOwAEAA4AAABIAAAAAQAAACsABAAGAAAAYgAAAAAAgD8gAAQAZwAAAAMAAAANAAAAOwAEAGcAAABoAAAAAwAAADYABQACAAAA" ++
        "BAAAAAAAAAADAAAA+AACAAUAAAA9AAQABwAAAAwAAAALAAAAPQAEAA0AAAAQAAAADwAAAE8ABwAHAAAAEQAAABAAAAAQAAAAAAAA" ++
        "AAEAAACDAAUABwAAABIAAAAMAAAAEQAAAE8ABwAHAAAAFAAAABAAAAAQAAAAAgAAAAMAAACIAAUABwAAABUAAAASAAAAFAAAAD0A" ++
        "BAANAAAAGAAAABcAAABPAAcABwAAABkAAAAYAAAAGAAAAAAAAAABAAAATwAHAAcAAAAcAAAAGAAAABgAAAACAAAAAwAAAIUABQAH" ++
        "AAAAHQAAABUAAAAcAAAAgQAFAAcAAAAeAAAAGQAAAB0AAABBAAUAJAAAACUAAAAhAAAAIwAAAD0ABAAHAAAAJgAAACUAAACIAAUA" ++
        "BwAAACcAAAAeAAAAJgAAAD0ABAArAAAALgAAAC0AAABXAAUADQAAADAAAAAuAAAAJwAAAEEABQAyAAAAMwAAACEAAAAxAAAAPQAE" ++
        "AAYAAAA0AAAAMwAAALoABQA2AAAANwAAADQAAAA1AAAA9wADADkAAAAAAAAA+gAEADcAAAA4AAAAOQAAAPgAAgA4AAAATwAJAA0A" ++
        "AAA7AAAAMAAAADAAAAACAAAAAQAAAAAAAAADAAAA+QACADkAAAD4AAIAOQAAAPUABwANAAAAdAAAADAAAAAFAAAAOwAAADgAAABB" ++
        "AAUAPwAAAEAAAAA8AAAAPgAAAD0ABAAGAAAAQQAAAEAAAAC6AAUANgAAAEMAAABBAAAAQgAAAPcAAwBFAAAAAAAAAPoABABDAAAA" ++
        "RAAAAEUAAAD4AAIARAAAAD0ABAANAAAASQAAAEgAAABPAAcABwAAAEoAAABJAAAASQAAAAAAAAABAAAAUAAFAAcAAABNAAAAQQAA" ++
        "AEEAAACBAAUABwAAAE4AAABKAAAATQAAAE8ABwAHAAAAUgAAAEkAAABJAAAAAgAAAAMAAACBAAUABwAAAFMAAABKAAAAUgAAAIMA" ++
        "BQAHAAAAVwAAAFMAAABNAAAADAAIAAcAAABYAAAAAQAAACsAAAAMAAAATgAAAFcAAACBAAUABgAAAF0AAABBAAAANQAAAAwABwAG" ++
        "AAAAYAAAAAEAAABDAAAADAAAAFgAAACDAAUABgAAAGEAAABdAAAAYAAAAAwACAAGAAAAYwAAAAEAAAArAAAAYQAAAEIAAABiAAAA" ++
        "jgAFAA0AAABmAAAAdAAAAGMAAAD5AAIARQAAAPgAAgBFAAAA9QAHAA0AAAB1AAAAdAAAADkAAABmAAAARAAAAPcAAwBuAAAAAAAA" ++
        "APoABAA3AAAAbQAAAHEAAAD4AAIAbQAAAE8ACQANAAAAcAAAAHUAAAB1AAAAAgAAAAEAAAAAAAAAAwAAAPkAAgBuAAAA+AACAHEA" ++
        "AAD5AAIAbgAAAPgAAgBuAAAA9QAHAA0AAAB2AAAAcAAAAG0AAAB1AAAAcQAAAD4AAwBoAAAAdgAAAP0AAQA4AAEA",
);

pub const shadow_instanced = decodeSpirv(
    "AwIjBwAAAQALAA0AagAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ACgAEAAAABAAA" ++
        "AG1haW4AAAAACwAAAA8AAAAcAAAATwAAAFQAAAAQAAMABAAAAAcAAABHAAQACwAAAB4AAAAAAAAARwADAA8AAAAOAAAARwAEAA8A" ++
        "AAAeAAAABAAAAEcAAwAcAAAADgAAAEcABAAcAAAAHgAAAAUAAABHAAMATwAAAA4AAABHAAQATwAAAB4AAAADAAAARwAEAFQAAAAe" ++
        "AAAAAAAAAEcAAwBVAAAAAgAAAEgABQBVAAAAAAAAACMAAAAAAAAASAAFAFUAAAABAAAAIwAAAAgAAABIAAUAVQAAAAIAAAAjAAAA" ++
        "EAAAABMAAgACAAAAIQADAAMAAAACAAAAFgADAAYAAAAgAAAAFwAEAAcAAAAGAAAAAgAAACAABAAKAAAAAQAAAAcAAAA7AAQACgAA" ++
        "AAsAAAABAAAAFwAEAA0AAAAGAAAABAAAACAABAAOAAAAAQAAAA0AAAA7AAQADgAAAA8AAAABAAAAKwAEAAYAAAAUAAAAAAAAPzsA" ++
        "BAAOAAAAHAAAAAEAAAAVAAQAHQAAACAAAAAAAAAAKwAEAB0AAAAeAAAAAAAAACAABAAfAAAAAQAAAAYAAAArAAQABgAAACgAAAAA" ++
        "AAAALAAFAAcAAAApAAAAKAAAACgAAAArAAQAHQAAAC4AAAABAAAAFAACADoAAAArAAQABgAAAEAAAAAAAABAKwAEAAYAAABGAAAA" ++
        "AACAPzsABAAOAAAATwAAAAEAAAAgAAQAUwAAAAMAAAANAAAAOwAEAFMAAABUAAAAAwAAAB4ABQBVAAAABwAAAAcAAAAGAAAAIAAE" ++
        "AFYAAAAJAAAAVQAAADsABABWAAAAVwAAAAkAAAAVAAQAWAAAACAAAAABAAAAKwAEAFgAAABZAAAAAgAAACAABABaAAAACQAAAAYA" ++
        "AAA2AAUAAgAAAAQAAAAAAAAAAwAAAPgAAgAFAAAAPQAEAAcAAAAMAAAACwAAAD0ABAANAAAAEAAAAA8AAABPAAcABwAAABEAAAAQ" ++
        "AAAAEAAAAAAAAAABAAAATwAHAAcAAAATAAAAEAAAABAAAAACAAAAAwAAAI4ABQAHAAAAFQAAABMAAAAUAAAAgQAFAAcAAAAWAAAA" ++
        "EQAAABUAAACDAAUABwAAABcAAAAMAAAAFgAAAAwABgAHAAAAGAAAAAEAAAAEAAAAFwAAAEEABQAfAAAAIAAAABwAAAAeAAAAPQAE" ++
        "AAYAAAAhAAAAIAAAAFAABQAHAAAAIgAAACEAAAAhAAAAgwAFAAcAAAAjAAAAFQAAACIAAACDAAUABwAAACQAAAAYAAAAIwAAAAwA" ++
        "BwAHAAAAKgAAAAEAAAAoAAAAJAAAACkAAAAMAAYABgAAACsAAAABAAAAQgAAACoAAABRAAUABgAAAC0AAAAkAAAAAAAAAFEABQAG" ++
        "AAAAMAAAACQAAAABAAAADAAHAAYAAAAxAAAAAQAAACgAAAAtAAAAMAAAAAwABwAGAAAAMgAAAAEAAAAlAAAAMQAAACgAAACBAAUA" ++
        "BgAAADMAAAArAAAAMgAAAIMABQAGAAAANgAAADMAAAAhAAAAQQAFAB8AAAA4AAAAHAAAAC4AAAA9AAQABgAAADkAAAA4AAAAugAF" ++
        "ADoAAAA7AAAAOQAAACgAAAD3AAMAPgAAAAAAAAD6AAQAOwAAAD0AAABIAAAA+AACAD0AAACFAAUABgAAAEMAAABAAAAAOQAAAIgA" ++
        "BQAGAAAARAAAADYAAABDAAAAgwAFAAYAAABFAAAAFAAAAEQAAAAMAAgABgAAAEcAAAABAAAAKwAAAEUAAAAoAAAARgAAAPkAAgA+" ++
        "AAAA+AACAEgAAACDAAUABgAAAEoAAAAUAAAANgAAAAwACAAGAAAASwAAAAEAAAArAAAASgAAACgAAABGAAAA+QACAD4AAAD4AAIA" ++
        "PgAAAPUABwAGAAAAaAAAAEcAAAA9AAAASwAAAEgAAAA9AAQADQAAAFAAAABPAAAAjgAFAA0AAABSAAAAUAAAAGgAAABBAAUAWgAA" ++
        "AFsAAABXAAAAWQAAAD0ABAAGAAAAXAAAAFsAAAC6AAUAOgAAAF0AAABcAAAAFAAAAPcAAwBgAAAAAAAAAPoABABdAAAAXwAAAGMA" ++
        "AAD4AAIAXwAAAE8ACQANAAAAYgAAAFIAAABSAAAAAgAAAAEAAAAAAAAAAwAAAPkAAgBgAAAA+AACAGMAAAD5AAIAYAAAAPgAAgBg" ++
        "AAAA9QAHAA0AAABpAAAAYgAAAF8AAABSAAAAYwAAAD4AAwBUAAAAaQAAAP0AAQA4AAEA",
);

pub const blur_horizontal = decodeSpirv("AwIjBwAAAQALAA0AXAAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ACAAEAAAABAAAAG1haW4AAAAADQAAABQAAABQAAAAEAADAAQAAAAHAAAARwAEAA0AAAAeAAAAAAAAAEcAAwAUAAAADgAAAEcABAAUAAAAHgAAAAUAAABHAAMALQAAAAIAAABIAAUALQAAAAAAAAAjAAAAAAAAAEgABQAtAAAAAQAAACMAAAAIAAAASAAFAC0AAAACAAAAIwAAABAAAABHAAQAQAAAACEAAAAAAAAARwAEAEAAAAAiAAAAAAAAAEcABABQAAAAHgAAAAAAAAATAAIAAgAAACEAAwADAAAAAgAAABUABAAGAAAAIAAAAAEAAAAXAAQABwAAAAYAAAACAAAAFgADAAoAAAAgAAAAFwAEAAsAAAAKAAAAAgAAACAABAAMAAAAAQAAAAsAAAA7AAQADAAAAA0AAAABAAAAFwAEABIAAAAKAAAABAAAACAABAATAAAAAQAAABIAAAA7AAQAEwAAABQAAAABAAAAFQAEABUAAAAgAAAAAAAAACsABAAVAAAAFgAAAAAAAAAgAAQAFwAAAAEAAAAKAAAAKwAEAAoAAAAdAAAAAAAAACwABwASAAAAHgAAAB0AAAAdAAAAHQAAAB0AAAArAAQABgAAACAAAAAAAAAAHgAFAC0AAAALAAAACwAAAAoAAAAgAAQALgAAAAkAAAAtAAAAOwAEAC4AAAAvAAAACQAAACsABAAGAAAAMAAAAAEAAAAgAAQAMQAAAAkAAAAKAAAAFAACADsAAAAZAAkAPQAAAAoAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAbAAMAPgAAAD0AAAAgAAQAPwAAAAAAAAA+AAAAOwAEAD8AAABAAAAAAAAAACAABABPAAAAAwAAABIAAAA7AAQATwAAAFAAAAADAAAANgAFAAIAAAAEAAAAAAAAAAMAAAD4AAIABQAAAD0ABAALAAAADgAAAA0AAABuAAQABwAAAA8AAAAOAAAAQQAFABcAAAAYAAAAFAAAABYAAAA9AAQACgAAABkAAAAYAAAAbgAEAAYAAAAaAAAAGQAAAFEABQAGAAAAIwAAAA8AAAAAAAAAggAFAAYAAAAlAAAAIwAAABoAAAAMAAcABgAAACYAAAABAAAAKgAAACAAAAAlAAAA+QACACcAAAD4AAIAJwAAAPUABwAGAAAAWwAAACAAAAAFAAAATAAAACgAAAD1AAcAEgAAAFoAAAAeAAAABQAAAEoAAAAoAAAA9QAHAAYAAABZAAAAJgAAAAUAAABOAAAAKAAAAEEABgAxAAAAMgAAAC8AAAAwAAAAFgAAAD0ABAAKAAAAMwAAADIAAABuAAQABgAAADQAAAAzAAAAggAFAAYAAAA1AAAANAAAADAAAACAAAUABgAAADkAAAAjAAAAGgAAAAwABwAGAAAAOgAAAAEAAAAnAAAANQAAADkAAACzAAUAOwAAADwAAABZAAAAOgAAAPYABAApAAAAKAAAAAAAAAD6AAQAPAAAACgAAAApAAAA+AACACgAAAA9AAQAPgAAAEEAAABAAAAAUQAFAAYAAABFAAAADwAAAAEAAABQAAUABwAAAEYAAABZAAAARQAAAGQABAA9AAAARwAAAEEAAABfAAcAEgAAAEgAAABHAAAARgAAAAIAAAAgAAAAgQAFABIAAABKAAAAWgAAAEgAAACAAAUABgAAAEwAAABbAAAAMAAAAIAABQAGAAAATgAAAFkAAAAwAAAA+QACACcAAAD4AAIAKQAAAG8ABAAKAAAAUwAAAFsAAABQAAcAEgAAAFQAAABTAAAAUwAAAFMAAABTAAAAiAAFABIAAABVAAAAWgAAAFQAAAA+AAMAUAAAAFUAAAD9AAEAOAABAA==");

pub const blur_vertical = decodeSpirv("AwIjBwAAAQALAA0AkAAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ACQAEAAAABAAAAG1haW4AAAAADQAAABQAAABdAAAAhgAAABAAAwAEAAAABwAAAEcABAANAAAAHgAAAAAAAABHAAMAFAAAAA4AAABHAAQAFAAAAB4AAAAFAAAARwADAC4AAAACAAAASAAFAC4AAAAAAAAAIwAAAAAAAABIAAUALgAAAAEAAAAjAAAACAAAAEgABQAuAAAAAgAAACMAAAAQAAAARwAEAEEAAAAhAAAAAAAAAEcABABBAAAAIgAAAAAAAABHAAMAXQAAAA4AAABHAAQAXQAAAB4AAAAEAAAARwAEAIYAAAAeAAAAAAAAABMAAgACAAAAIQADAAMAAAACAAAAFQAEAAYAAAAgAAAAAQAAABcABAAHAAAABgAAAAIAAAAWAAMACgAAACAAAAAXAAQACwAAAAoAAAACAAAAIAAEAAwAAAABAAAACwAAADsABAAMAAAADQAAAAEAAAAXAAQAEgAAAAoAAAAEAAAAIAAEABMAAAABAAAAEgAAADsABAATAAAAFAAAAAEAAAAVAAQAFQAAACAAAAAAAAAAKwAEABUAAAAWAAAAAAAAACAABAAXAAAAAQAAAAoAAAArAAQACgAAAB0AAAAAAAAALAAHABIAAAAeAAAAHQAAAB0AAAAdAAAAHQAAACsABAAGAAAAIAAAAAAAAAArAAQAFQAAACIAAAABAAAAHgAFAC4AAAALAAAACwAAAAoAAAAgAAQALwAAAAkAAAAuAAAAOwAEAC8AAAAwAAAACQAAACsABAAGAAAAMQAAAAEAAAAgAAQAMgAAAAkAAAAKAAAAFAACADwAAAAZAAkAPgAAAAoAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAbAAMAPwAAAD4AAAAgAAQAQAAAAAAAAAA/AAAAOwAEAEAAAABBAAAAAAAAADsABAATAAAAXQAAAAEAAAArAAQACgAAAHIAAAAAAAA/KwAEAAoAAAB4AAAAAACAPysABAAGAAAAfQAAAAIAAAAgAAQAhQAAAAMAAAASAAAAOwAEAIUAAACGAAAAAwAAADYABQACAAAABAAAAAAAAAADAAAA+AACAAUAAAA9AAQACwAAAA4AAAANAAAAbgAEAAcAAAAPAAAADgAAAEEABQAXAAAAGAAAABQAAAAWAAAAPQAEAAoAAAAZAAAAGAAAAG4ABAAGAAAAGgAAABkAAABRAAUABgAAACQAAAAPAAAAAQAAAIIABQAGAAAAJgAAACQAAAAaAAAADAAHAAYAAAAnAAAAAQAAACoAAAAgAAAAJgAAAPkAAgAoAAAA+AACACgAAAD1AAcABgAAAI0AAAAgAAAABQAAAEwAAAApAAAA9QAHABIAAACMAAAAHgAAAAUAAABKAAAAKQAAAPUABwAGAAAAiwAAACcAAAAFAAAATgAAACkAAABBAAYAMgAAADMAAAAwAAAAMQAAACIAAAA9AAQACgAAADQAAAAzAAAAbgAEAAYAAAA1AAAANAAAAIIABQAGAAAANgAAADUAAAAxAAAAgAAFAAYAAAA6AAAAJAAAABoAAAAMAAcABgAAADsAAAABAAAAJwAAADYAAAA6AAAAswAFADwAAAA9AAAAiwAAADsAAAD2AAQAKgAAACkAAAAAAAAA+gAEAD0AAAApAAAAKgAAAPgAAgApAAAAPQAEAD8AAABCAAAAQQAAAFEABQAGAAAARAAAAA8AAAAAAAAAUAAFAAcAAABGAAAARAAAAIsAAABkAAQAPgAAAEcAAABCAAAAXwAHABIAAABIAAAARwAAAEYAAAACAAAAIAAAAIEABQASAAAASgAAAIwAAABIAAAAgAAFAAYAAABMAAAAjQAAADEAAACAAAUABgAAAE4AAACLAAAAMQAAAPkAAgAoAAAA+AACACoAAABvAAQACgAAAFIAAACNAAAAUAAHABIAAABTAAAAUgAAAFIAAABSAAAAUgAAAIgABQASAAAAVAAAAIwAAABTAAAAQQAFABcAAABVAAAAFAAAACIAAAA9AAQACgAAAFYAAABVAAAAugAFADwAAABXAAAAVgAAAB0AAAD3AAMAWQAAAAAAAAD6AAQAVwAAAFgAAABZAAAA+AACAFgAAAA9AAQAEgAAAF4AAABdAAAATwAHAAsAAABfAAAAXgAAAF4AAAAAAAAAAQAAAFAABQALAAAAYgAAAFYAAABWAAAAgQAFAAsAAABjAAAAXwAAAGIAAABPAAcACwAAAGcAAABeAAAAXgAAAAIAAAADAAAAgQAFAAsAAABoAAAAXwAAAGcAAACDAAUACwAAAGwAAABoAAAAYgAAAAwACAALAAAAbQAAAAEAAAArAAAADgAAAGMAAABsAAAAgQAFAAoAAABzAAAAVgAAAHIAAAAMAAcACgAAAHYAAAABAAAAQwAAAA4AAABtAAAAgwAFAAoAAAB3AAAAcwAAAHYAAAAMAAgACgAAAHkAAAABAAAAKwAAAHcAAAAdAAAAeAAAAI4ABQASAAAAfAAAAFQAAAB5AAAA+QACAFkAAAD4AAIAWQAAAPUABwASAAAAjgAAAFQAAAAqAAAAfAAAAFgAAABBAAUAMgAAAH4AAAAwAAAAfQAAAD0ABAAKAAAAfwAAAH4AAAC6AAUAPAAAAIAAAAB/AAAAcgAAAPcAAwCCAAAAAAAAAPoABACAAAAAgQAAAIIAAAD4AAIAgQAAAE8ACQASAAAAhAAAAI4AAACOAAAAAgAAAAEAAAAAAAAAAwAAAPkAAgCCAAAA+AACAIIAAAD1AAcAEgAAAI8AAACOAAAAWQAAAIQAAACBAAAAPgADAIYAAACPAAAA/QABADgAAQA=");

pub const blur_vertical_pure = decodeSpirv("AwIjBwAAAQALAA0AXAAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ACAAEAAAABAAAAG1haW4AAAAADQAAABQAAABQAAAAEAADAAQAAAAHAAAARwAEAA0AAAAeAAAAAAAAAEcAAwAUAAAADgAAAEcABAAUAAAAHgAAAAUAAABHAAMALgAAAAIAAABIAAUALgAAAAAAAAAjAAAAAAAAAEgABQAuAAAAAQAAACMAAAAIAAAASAAFAC4AAAACAAAAIwAAABAAAABHAAQAQQAAACEAAAAAAAAARwAEAEEAAAAiAAAAAAAAAEcABABQAAAAHgAAAAAAAAATAAIAAgAAACEAAwADAAAAAgAAABUABAAGAAAAIAAAAAEAAAAXAAQABwAAAAYAAAACAAAAFgADAAoAAAAgAAAAFwAEAAsAAAAKAAAAAgAAACAABAAMAAAAAQAAAAsAAAA7AAQADAAAAA0AAAABAAAAFwAEABIAAAAKAAAABAAAACAABAATAAAAAQAAABIAAAA7AAQAEwAAABQAAAABAAAAFQAEABUAAAAgAAAAAAAAACsABAAVAAAAFgAAAAAAAAAgAAQAFwAAAAEAAAAKAAAAKwAEAAoAAAAdAAAAAAAAACwABwASAAAAHgAAAB0AAAAdAAAAHQAAAB0AAAArAAQABgAAACAAAAAAAAAAKwAEABUAAAAiAAAAAQAAAB4ABQAuAAAACwAAAAsAAAAKAAAAIAAEAC8AAAAJAAAALgAAADsABAAvAAAAMAAAAAkAAAArAAQABgAAADEAAAABAAAAIAAEADIAAAAJAAAACgAAABQAAgA8AAAAGQAJAD4AAAAKAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAGwADAD8AAAA+AAAAIAAEAEAAAAAAAAAAPwAAADsABABAAAAAQQAAAAAAAAAgAAQATwAAAAMAAAASAAAAOwAEAE8AAABQAAAAAwAAADYABQACAAAABAAAAAAAAAADAAAA+AACAAUAAAA9AAQACwAAAA4AAAANAAAAbgAEAAcAAAAPAAAADgAAAEEABQAXAAAAGAAAABQAAAAWAAAAPQAEAAoAAAAZAAAAGAAAAG4ABAAGAAAAGgAAABkAAABRAAUABgAAACQAAAAPAAAAAQAAAIIABQAGAAAAJgAAACQAAAAaAAAADAAHAAYAAAAnAAAAAQAAACoAAAAgAAAAJgAAAPkAAgAoAAAA+AACACgAAAD1AAcABgAAAFsAAAAgAAAABQAAAEwAAAApAAAA9QAHABIAAABaAAAAHgAAAAUAAABKAAAAKQAAAPUABwAGAAAAWQAAACcAAAAFAAAATgAAACkAAABBAAYAMgAAADMAAAAwAAAAMQAAACIAAAA9AAQACgAAADQAAAAzAAAAbgAEAAYAAAA1AAAANAAAAIIABQAGAAAANgAAADUAAAAxAAAAgAAFAAYAAAA6AAAAJAAAABoAAAAMAAcABgAAADsAAAABAAAAJwAAADYAAAA6AAAAswAFADwAAAA9AAAAWQAAADsAAAD2AAQAKgAAACkAAAAAAAAA+gAEAD0AAAApAAAAKgAAAPgAAgApAAAAPQAEAD8AAABCAAAAQQAAAFEABQAGAAAARAAAAA8AAAAAAAAAUAAFAAcAAABGAAAARAAAAFkAAABkAAQAPgAAAEcAAABCAAAAXwAHABIAAABIAAAARwAAAEYAAAACAAAAIAAAAIEABQASAAAASgAAAFoAAABIAAAAgAAFAAYAAABMAAAAWwAAADEAAACAAAUABgAAAE4AAABZAAAAMQAAAPkAAgAoAAAA+AACACoAAABvAAQACgAAAFMAAABbAAAAUAAHABIAAABUAAAAUwAAAFMAAABTAAAAUwAAAIgABQASAAAAVQAAAFoAAABUAAAAPgADAFAAAABVAAAA/QABADgAAQA=");

pub const blur_horizontal_paired = decodeSpirv("AwIjBwAAAQALAA0ArQAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ACAAEAAAABAAAAG1haW4AAAAADQAAABQAAACaAAAAEAADAAQAAAAHAAAARwAEAA0AAAAeAAAAAAAAAEcAAwAUAAAADgAAAEcABAAUAAAAHgAAAAUAAABHAAMAIgAAAAIAAABIAAUAIgAAAAAAAAAjAAAAAAAAAEgABQAiAAAAAQAAACMAAAAIAAAASAAFACIAAAACAAAAIwAAABAAAABHAAQAPwAAACEAAAAAAAAARwAEAD8AAAAiAAAAAAAAAEcABACaAAAAHgAAAAAAAAATAAIAAgAAACEAAwADAAAAAgAAABUABAAGAAAAIAAAAAEAAAAXAAQABwAAAAYAAAACAAAAFgADAAoAAAAgAAAAFwAEAAsAAAAKAAAAAgAAACAABAAMAAAAAQAAAAsAAAA7AAQADAAAAA0AAAABAAAAFwAEABIAAAAKAAAABAAAACAABAATAAAAAQAAABIAAAA7AAQAEwAAABQAAAABAAAAFQAEABUAAAAgAAAAAAAAACsABAAVAAAAFgAAAAAAAAAgAAQAFwAAAAEAAAAKAAAAHgAFACIAAAALAAAACwAAAAoAAAAgAAQAIwAAAAkAAAAiAAAAOwAEACMAAAAkAAAACQAAACsABAAGAAAAJQAAAAEAAAAgAAQAJgAAAAkAAAAKAAAAKwAEAAoAAAAzAAAAAAAAPywABQALAAAANAAAADMAAAAzAAAAIAAEADYAAAAJAAAACwAAABkACQA8AAAACgAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAABsAAwA9AAAAPAAAACAABAA+AAAAAAAAAD0AAAA7AAQAPgAAAD8AAAAAAAAAKwAEAAYAAABCAAAAAAAAABQAAgBNAAAAKwAEAAoAAABUAAAAAAAAQCsABAAKAAAAWgAAAAAAAAArAAQABgAAAG4AAAACAAAAIAAEAJkAAAADAAAAEgAAADsABACZAAAAmgAAAAMAAAA2AAUAAgAAAAQAAAAAAAAAAwAAAPgAAgAFAAAAPQAEAAsAAAAOAAAADQAAAG4ABAAHAAAADwAAAA4AAABBAAUAFwAAABgAAAAUAAAAFgAAAD0ABAAKAAAAGQAAABgAAABuAAQABgAAABoAAAAZAAAAUQAFAAYAAAAeAAAADwAAAAAAAAAMAAcABgAAAB8AAAABAAAAJwAAABoAAAAeAAAAQQAGACYAAAAnAAAAJAAAACUAAAAWAAAAPQAEAAoAAAAoAAAAJwAAAG4ABAAGAAAAKQAAACgAAACCAAUABgAAACoAAAApAAAAJQAAAIIABQAGAAAALQAAACoAAAAeAAAADAAHAAYAAAAuAAAAAQAAACcAAAAaAAAALQAAAG8ABAALAAAAMgAAAA8AAACBAAUACwAAADUAAAAyAAAANAAAAEEABQA2AAAANwAAACQAAAAlAAAAPQAEAAsAAAA4AAAANwAAAIgABQALAAAAOQAAADUAAAA4AAAAPQAEAD0AAABAAAAAPwAAAGQABAA8AAAAQwAAAEAAAABfAAcAEgAAAEQAAABDAAAADwAAAAIAAABCAAAA+QACAEYAAAD4AAIARgAAAPUABwASAAAAqAAAAEQAAAAFAAAAqwAAAEkAAAD1AAcABgAAAKUAAAAlAAAABQAAAHAAAABJAAAAswAFAE0AAABOAAAApQAAAB8AAAD2AAQASAAAAEkAAAAAAAAA+gAEAE4AAABHAAAASAAAAPgAAgBHAAAAsQAFAE0AAABRAAAApQAAAB8AAAD3AAMAUwAAAAAAAAD6AAQAUQAAAFIAAABkAAAA+AACAFIAAAA9AAQAPQAAAFUAAAA/AAAAbwAEAAoAAABYAAAApQAAAIEABQAKAAAAWQAAAFgAAAAzAAAAUAAFAAsAAABbAAAAWQAAAFoAAACIAAUACwAAAF4AAABbAAAAOAAAAIMABQALAAAAXwAAADkAAABeAAAAVwAFABIAAABgAAAAVQAAAF8AAACOAAUAEgAAAGEAAABgAAAAVAAAAIEABQASAAAAYwAAAKgAAABhAAAA+QACAFMAAAD4AAIAZAAAAD0ABAA9AAAAZQAAAD8AAABQAAUABwAAAGgAAAClAAAAQgAAAIIABQAHAAAAaQAAAA8AAABoAAAAZAAEADwAAABqAAAAZQAAAF8ABwASAAAAawAAAGoAAABpAAAAAgAAAEIAAACBAAUAEgAAAG0AAACoAAAAawAAAPkAAgBTAAAA+AACAFMAAAD1AAcAEgAAAKsAAABjAAAAUgAAAG0AAABkAAAA+QACAEkAAAD4AAIASQAAAIAABQAGAAAAcAAAAKUAAABuAAAA+QACAEYAAAD4AAIASAAAAPkAAgByAAAA+AACAHIAAAD1AAcAEgAAAKcAAACoAAAASAAAAKwAAAB1AAAA9QAHAAYAAACmAAAAJQAAAEgAAACYAAAAdQAAALMABQBNAAAAeQAAAKYAAAAuAAAA9gAEAHQAAAB1AAAAAAAAAPoABAB5AAAAcwAAAHQAAAD4AAIAcwAAALEABQBNAAAAfAAAAKYAAAAuAAAA9wADAH4AAAAAAAAA+gAEAHwAAAB9AAAAjQAAAPgAAgB9AAAAPQAEAD0AAAB/AAAAPwAAAG8ABAAKAAAAggAAAKYAAACBAAUACgAAAIMAAACCAAAAMwAAAFAABQALAAAAhAAAAIMAAABaAAAAiAAFAAsAAACHAAAAhAAAADgAAACBAAUACwAAAIgAAAA5AAAAhwAAAFcABQASAAAAiQAAAH8AAACIAAAAjgAFABIAAACKAAAAiQAAAFQAAACBAAUAEgAAAIwAAACnAAAAigAAAPkAAgB+AAAA+AACAI0AAAA9AAQAPQAAAI4AAAA/AAAAUAAFAAcAAACRAAAApgAAAEIAAACAAAUABwAAAJIAAAAPAAAAkQAAAGQABAA8AAAAkwAAAI4AAABfAAcAEgAAAJQAAACTAAAAkgAAAAIAAABCAAAAgQAFABIAAACWAAAApwAAAJQAAAD5AAIAfgAAAPgAAgB+AAAA9QAHABIAAACsAAAAjAAAAH0AAACWAAAAjQAAAPkAAgB1AAAA+AACAHUAAACAAAUABgAAAJgAAACmAAAAbgAAAPkAAgByAAAA+AACAHQAAACAAAUABgAAAJ0AAAAlAAAAHwAAAIAABQAGAAAAnwAAAJ0AAAAuAAAAbwAEAAoAAACgAAAAnwAAAFAABwASAAAAoQAAAKAAAACgAAAAoAAAAKAAAACIAAUAEgAAAKIAAACnAAAAoQAAAD4AAwCaAAAAogAAAP0AAQA4AAEA");

pub const blur_vertical_paired = decodeSpirv("AwIjBwAAAQALAA0ArgAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ACAAEAAAABAAAAG1haW4AAAAADQAAABQAAACbAAAAEAADAAQAAAAHAAAARwAEAA0AAAAeAAAAAAAAAEcAAwAUAAAADgAAAEcABAAUAAAAHgAAAAUAAABHAAMAIwAAAAIAAABIAAUAIwAAAAAAAAAjAAAAAAAAAEgABQAjAAAAAQAAACMAAAAIAAAASAAFACMAAAACAAAAIwAAABAAAABHAAQAQAAAACEAAAAAAAAARwAEAEAAAAAiAAAAAAAAAEcABACbAAAAHgAAAAAAAAATAAIAAgAAACEAAwADAAAAAgAAABUABAAGAAAAIAAAAAEAAAAXAAQABwAAAAYAAAACAAAAFgADAAoAAAAgAAAAFwAEAAsAAAAKAAAAAgAAACAABAAMAAAAAQAAAAsAAAA7AAQADAAAAA0AAAABAAAAFwAEABIAAAAKAAAABAAAACAABAATAAAAAQAAABIAAAA7AAQAEwAAABQAAAABAAAAFQAEABUAAAAgAAAAAAAAACsABAAVAAAAFgAAAAAAAAAgAAQAFwAAAAEAAAAKAAAAKwAEABUAAAAdAAAAAQAAAB4ABQAjAAAACwAAAAsAAAAKAAAAIAAEACQAAAAJAAAAIwAAADsABAAkAAAAJQAAAAkAAAArAAQABgAAACYAAAABAAAAIAAEACcAAAAJAAAACgAAACsABAAKAAAANAAAAAAAAD8sAAUACwAAADUAAAA0AAAANAAAACAABAA3AAAACQAAAAsAAAAZAAkAPQAAAAoAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAbAAMAPgAAAD0AAAAgAAQAPwAAAAAAAAA+AAAAOwAEAD8AAABAAAAAAAAAACsABAAGAAAAQwAAAAAAAAAUAAIATgAAACsABAAKAAAAVQAAAAAAAEArAAQACgAAAFgAAAAAAAAAKwAEAAYAAABvAAAAAgAAACAABACaAAAAAwAAABIAAAA7AAQAmgAAAJsAAAADAAAANgAFAAIAAAAEAAAAAAAAAAMAAAD4AAIABQAAAD0ABAALAAAADgAAAA0AAABuAAQABwAAAA8AAAAOAAAAQQAFABcAAAAYAAAAFAAAABYAAAA9AAQACgAAABkAAAAYAAAAbgAEAAYAAAAaAAAAGQAAAFEABQAGAAAAHwAAAA8AAAABAAAADAAHAAYAAAAgAAAAAQAAACcAAAAaAAAAHwAAAEEABgAnAAAAKAAAACUAAAAmAAAAHQAAAD0ABAAKAAAAKQAAACgAAABuAAQABgAAACoAAAApAAAAggAFAAYAAAArAAAAKgAAACYAAACCAAUABgAAAC4AAAArAAAAHwAAAAwABwAGAAAALwAAAAEAAAAnAAAAGgAAAC4AAABvAAQACwAAADMAAAAPAAAAgQAFAAsAAAA2AAAAMwAAADUAAABBAAUANwAAADgAAAAlAAAAJgAAAD0ABAALAAAAOQAAADgAAACIAAUACwAAADoAAAA2AAAAOQAAAD0ABAA+AAAAQQAAAEAAAABkAAQAPQAAAEQAAABBAAAAXwAHABIAAABFAAAARAAAAA8AAAACAAAAQwAAAPkAAgBHAAAA+AACAEcAAAD1AAcAEgAAAKkAAABFAAAABQAAAKwAAABKAAAA9QAHAAYAAACmAAAAJgAAAAUAAABxAAAASgAAALMABQBOAAAATwAAAKYAAAAgAAAA9gAEAEkAAABKAAAAAAAAAPoABABPAAAASAAAAEkAAAD4AAIASAAAALEABQBOAAAAUgAAAKYAAAAgAAAA9wADAFQAAAAAAAAA+gAEAFIAAABTAAAAZQAAAPgAAgBTAAAAPQAEAD4AAABWAAAAQAAAAG8ABAAKAAAAWgAAAKYAAACBAAUACgAAAFsAAABaAAAANAAAAFAABQALAAAAXAAAAFgAAABbAAAAiAAFAAsAAABfAAAAXAAAADkAAACDAAUACwAAAGAAAAA6AAAAXwAAAFcABQASAAAAYQAAAFYAAABgAAAAjgAFABIAAABiAAAAYQAAAFUAAACBAAUAEgAAAGQAAACpAAAAYgAAAPkAAgBUAAAA+AACAGUAAAA9AAQAPgAAAGYAAABAAAAAUAAFAAcAAABpAAAAQwAAAKYAAACCAAUABwAAAGoAAAAPAAAAaQAAAGQABAA9AAAAawAAAGYAAABfAAcAEgAAAGwAAABrAAAAagAAAAIAAABDAAAAgQAFABIAAABuAAAAqQAAAGwAAAD5AAIAVAAAAPgAAgBUAAAA9QAHABIAAACsAAAAZAAAAFMAAABuAAAAZQAAAPkAAgBKAAAA+AACAEoAAACAAAUABgAAAHEAAACmAAAAbwAAAPkAAgBHAAAA+AACAEkAAAD5AAIAcwAAAPgAAgBzAAAA9QAHABIAAACoAAAAqQAAAEkAAACtAAAAdgAAAPUABwAGAAAApwAAACYAAABJAAAAmQAAAHYAAACzAAUATgAAAHoAAACnAAAALwAAAPYABAB1AAAAdgAAAAAAAAD6AAQAegAAAHQAAAB1AAAA+AACAHQAAACxAAUATgAAAH0AAACnAAAALwAAAPcAAwB/AAAAAAAAAPoABAB9AAAAfgAAAI4AAAD4AAIAfgAAAD0ABAA+AAAAgAAAAEAAAABvAAQACgAAAIMAAACnAAAAgQAFAAoAAACEAAAAgwAAADQAAABQAAUACwAAAIUAAABYAAAAhAAAAIgABQALAAAAiAAAAIUAAAA5AAAAgQAFAAsAAACJAAAAOgAAAIgAAABXAAUAEgAAAIoAAACAAAAAiQAAAI4ABQASAAAAiwAAAIoAAABVAAAAgQAFABIAAACNAAAAqAAAAIsAAAD5AAIAfwAAAPgAAgCOAAAAPQAEAD4AAACPAAAAQAAAAFAABQAHAAAAkgAAAEMAAACnAAAAgAAFAAcAAACTAAAADwAAAJIAAABkAAQAPQAAAJQAAACPAAAAXwAHABIAAACVAAAAlAAAAJMAAAACAAAAQwAAAIEABQASAAAAlwAAAKgAAACVAAAA+QACAH8AAAD4AAIAfwAAAPUABwASAAAArQAAAI0AAAB+AAAAlwAAAI4AAAD5AAIAdgAAAPgAAgB2AAAAgAAFAAYAAACZAAAApwAAAG8AAAD5AAIAcwAAAPgAAgB1AAAAgAAFAAYAAACeAAAAJgAAACAAAACAAAUABgAAAKAAAACeAAAALwAAAG8ABAAKAAAAoQAAAKAAAABQAAcAEgAAAKIAAAChAAAAoQAAAKEAAAChAAAAiAAFABIAAACjAAAAqAAAAKIAAAA+AAMAmwAAAKMAAAD9AAEAOAABAA==");

fn decodedSize(comptime encoded: []const u8) usize {
    return std.base64.standard.Decoder.calcSizeForSlice(encoded) catch unreachable;
}

fn decodeSpirv(comptime encoded: []const u8) [decodedSize(encoded) / @sizeOf(u32)]u32 {
    @setEvalBranchQuota(10_000);
    const byte_count = decodedSize(encoded);
    comptime std.debug.assert(byte_count % @sizeOf(u32) == 0);
    var bytes: [byte_count]u8 = undefined;
    _ = std.base64.standard.Decoder.decode(&bytes, encoded) catch unreachable;
    var words: [byte_count / @sizeOf(u32)]u32 = undefined;
    for (&words, 0..) |*word, index| {
        word.* = std.mem.readInt(u32, bytes[index * 4 ..][0..4], .little);
    }
    return words;
}
