//! Embedded SPIR-V for the Vulkan compositor pipelines.
//!
//! Regenerate after editing a GLSL source below with:
//! `glslc -O -fshader-stage=<stage> source.glsl -o shader.spv`.

const std = @import("std");

pub const quad_source =
    \\#version 450
    \\layout(push_constant) uniform Push {
    \\    vec2 target_size;
    \\    vec2 texture_size;
    \\    float swap_rb;
    \\} pc;
    \\layout(location=0) in vec4 in_dest;
    \\layout(location=1) in vec4 in_source;
    \\layout(location=2) in vec4 in_clip;
    \\layout(location=3) in vec4 in_color;
    \\layout(location=4) in vec4 in_rounded;
    \\layout(location=5) in vec4 in_parameters;
    \\layout(location=0) out vec2 pixel;
    \\layout(location=1) flat out vec4 dest;
    \\layout(location=2) flat out vec4 source;
    \\layout(location=3) flat out vec4 color;
    \\layout(location=4) flat out vec4 rounded;
    \\layout(location=5) flat out vec4 parameters;
    \\void main() {
    \\    vec2 q=vec2(float(gl_VertexIndex&1),float((gl_VertexIndex>>1)&1));
    \\    vec2 pos=in_clip.xy+q*in_clip.zw;
    \\    gl_Position=vec4(pos/pc.target_size*2.0-1.0,0,1);
    \\    pixel=pos;
    \\    dest=in_dest;
    \\    source=in_source;
    \\    color=in_color;
    \\    rounded=in_rounded;
    \\    parameters=in_parameters;
    \\}
;

pub const solid_source =
    \\#version 450
    \\layout(push_constant) uniform Push {
    \\    vec2 target_size;
    \\    vec2 texture_size;
    \\    float swap_rb;
    \\} pc;
    \\layout(location=3) flat in vec4 color;
    \\layout(location=0) out vec4 out_color;
    \\void main() { out_color=pc.swap_rb>0.5 ? color.bgra : color; }
;

pub const image_source =
    \\#version 450
    \\layout(set=0,binding=0) uniform sampler2D tex;
    \\layout(push_constant) uniform Push {
    \\    vec2 target_size;
    \\    vec2 texture_size;
    \\    float swap_rb;
    \\} pc;
    \\layout(location=0) in vec2 pixel;
    \\layout(location=1) flat in vec4 dest;
    \\layout(location=2) flat in vec4 source;
    \\layout(location=4) flat in vec4 rounded;
    \\layout(location=5) flat in vec4 parameters;
    \\layout(location=0) out vec4 out_color;
    \\void main() {
    \\    vec2 q=(pixel-dest.xy)/dest.zw;
    \\    vec2 transformed=source.xy+q*source.zw;
    \\    vec2 coordinate;
    \\    switch (int(parameters.y)) {
    \\        case 1: coordinate=vec2(transformed.y,pc.texture_size.y-transformed.x); break;
    \\        case 2: coordinate=pc.texture_size-transformed; break;
    \\        case 3: coordinate=vec2(pc.texture_size.x-transformed.y,transformed.x); break;
    \\        case 4: coordinate=vec2(pc.texture_size.x-transformed.x,transformed.y); break;
    \\        case 5: coordinate=pc.texture_size-transformed.yx; break;
    \\        case 6: coordinate=vec2(transformed.x,pc.texture_size.y-transformed.y); break;
    \\        case 7: coordinate=transformed.yx; break;
    \\        default: coordinate=transformed; break;
    \\    }
    \\    if (parameters.z>0.5) coordinate.y=pc.texture_size.y-coordinate.y;
    \\    vec2 uv=coordinate/pc.texture_size;
    \\    vec4 color=texture(tex,uv);
    \\    if (pc.swap_rb>0.5) color=color.bgra;
    \\    color*=parameters.w;
    \\    if (parameters.x>0.0) {
    \\        vec2 center=clamp(pixel,rounded.xy+vec2(parameters.x),rounded.xy+rounded.zw-vec2(parameters.x));
    \\        float coverage=clamp(parameters.x+0.5-distance(pixel,center),0.0,1.0);
    \\        color*=coverage;
    \\    }
    \\    out_color=pc.swap_rb>0.5 ? color.bgra : color;
    \\}
;

pub const image_alpha_instanced = decodeSpirv("AwIjBwAAAQALAA0A2gAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ACwAEAAAABAAA" ++
    "AG1haW4AAAAACwAAAA8AAAAXAAAAHwAAAJ8AAAC+AAAAEAADAAQAAAAHAAAARwAEAAsAAAAeAAAAAAAAAEcAAwAPAAAADgAAAEcA" ++
    "BAAPAAAAHgAAAAEAAABHAAMAFwAAAA4AAABHAAQAFwAAAB4AAAACAAAARwADAB8AAAAOAAAARwAEAB8AAAAeAAAABQAAAEcAAwA0" ++
    "AAAAAgAAAEgABQA0AAAAAAAAACMAAAAAAAAASAAFADQAAAABAAAAIwAAAAgAAABIAAUANAAAAAIAAAAjAAAAEAAAAEcABACGAAAA" ++
    "IQAAAAAAAABHAAQAhgAAACIAAAAAAAAARwADAJ8AAAAOAAAARwAEAJ8AAAAeAAAABAAAAEcABAC+AAAAHgAAAAAAAAATAAIAAgAA" ++
    "ACEAAwADAAAAAgAAABYAAwAGAAAAIAAAABcABAAHAAAABgAAAAIAAAAgAAQACgAAAAEAAAAHAAAAOwAEAAoAAAALAAAAAQAAABcA" ++
    "BAANAAAABgAAAAQAAAAgAAQADgAAAAEAAAANAAAAOwAEAA4AAAAPAAAAAQAAADsABAAOAAAAFwAAAAEAAAA7AAQADgAAAB8AAAAB" ++
    "AAAAFQAEACAAAAAgAAAAAAAAACsABAAgAAAAIQAAAAEAAAAgAAQAIgAAAAEAAAAGAAAAFQAEACUAAAAgAAAAAQAAAB4ABQA0AAAA" ++
    "BwAAAAcAAAAGAAAAIAAEADUAAAAJAAAANAAAADsABAA1AAAANgAAAAkAAAArAAQAJQAAADcAAAABAAAAIAAEADgAAAAJAAAABgAA" ++
    "ACsABAAgAAAAOwAAAAAAAAAgAAQAQQAAAAkAAAAHAAAAKwAEACAAAABuAAAAAgAAACsABAAGAAAAcQAAAAAAAD8UAAIAcgAAABkA" ++
    "CQCDAAAABgAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAABsAAwCEAAAAgwAAACAABACFAAAAAAAAAIQAAAA7AAQAhQAAAIYAAAAA" ++
    "AAAAKwAEACUAAACKAAAAAgAAACsABAAgAAAAkgAAAAMAAAArAAQABgAAAJkAAAAAAAAAOwAEAA4AAACfAAAAAQAAACsABAAGAAAA" ++
    "uAAAAAAAgD8gAAQAvQAAAAMAAAANAAAAOwAEAL0AAAC+AAAAAwAAADYABQACAAAABAAAAAAAAAADAAAA+AACAAUAAAA9AAQABwAA" ++
    "AAwAAAALAAAAPQAEAA0AAAAQAAAADwAAAE8ABwAHAAAAEQAAABAAAAAQAAAAAAAAAAEAAACDAAUABwAAABIAAAAMAAAAEQAAAE8A" ++
    "BwAHAAAAFAAAABAAAAAQAAAAAgAAAAMAAACIAAUABwAAABUAAAASAAAAFAAAAD0ABAANAAAAGAAAABcAAABPAAcABwAAABkAAAAY" ++
    "AAAAGAAAAAAAAAABAAAATwAHAAcAAAAcAAAAGAAAABgAAAACAAAAAwAAAIUABQAHAAAAHQAAABUAAAAcAAAAgQAFAAcAAAAeAAAA" ++
    "GQAAAB0AAABBAAUAIgAAACMAAAAfAAAAIQAAAD0ABAAGAAAAJAAAACMAAABuAAQAJQAAACYAAAAkAAAA9wADAC8AAAAAAAAA+wAR" ++
    "ACYAAAAuAAAAAQAAACcAAAACAAAAKAAAAAMAAAApAAAABAAAACoAAAAFAAAAKwAAAAYAAAAsAAAABwAAAC0AAAD4AAIALgAAAPkA" ++
    "AgAvAAAA+AACACcAAABRAAUABgAAADMAAAAeAAAAAQAAAEEABgA4AAAAOQAAADYAAAA3AAAAIQAAAD0ABAAGAAAAOgAAADkAAABR" ++
    "AAUABgAAAD0AAAAeAAAAAAAAAIMABQAGAAAAPgAAADoAAAA9AAAAUAAFAAcAAAA/AAAAMwAAAD4AAAD5AAIALwAAAPgAAgAoAAAA" ++
    "QQAFAEEAAABCAAAANgAAADcAAAA9AAQABwAAAEMAAABCAAAAgwAFAAcAAABFAAAAQwAAAB4AAAD5AAIALwAAAPgAAgApAAAAQQAG" ++
    "ADgAAABHAAAANgAAADcAAAA7AAAAPQAEAAYAAABIAAAARwAAAFEABQAGAAAASgAAAB4AAAABAAAAgwAFAAYAAABLAAAASAAAAEoA" ++
    "AABRAAUABgAAAE0AAAAeAAAAAAAAAFAABQAHAAAATgAAAEsAAABNAAAA+QACAC8AAAD4AAIAKgAAAEEABgA4AAAAUAAAADYAAAA3" ++
    "AAAAOwAAAD0ABAAGAAAAUQAAAFAAAABRAAUABgAAAFMAAAAeAAAAAAAAAIMABQAGAAAAVAAAAFEAAABTAAAAUQAFAAYAAABWAAAA" ++
    "HgAAAAEAAABQAAUABwAAAFcAAABUAAAAVgAAAPkAAgAvAAAA+AACACsAAABBAAUAQQAAAFkAAAA2AAAANwAAAD0ABAAHAAAAWgAA" ++
    "AFkAAABPAAcABwAAAFwAAAAeAAAAHgAAAAEAAAAAAAAAgwAFAAcAAABdAAAAWgAAAFwAAAD5AAIALwAAAPgAAgAsAAAAUQAFAAYA" ++
    "AABgAAAAHgAAAAAAAABBAAYAOAAAAGEAAAA2AAAANwAAACEAAAA9AAQABgAAAGIAAABhAAAAUQAFAAYAAABkAAAAHgAAAAEAAACD" ++
    "AAUABgAAAGUAAABiAAAAZAAAAFAABQAHAAAAZgAAAGAAAABlAAAA+QACAC8AAAD4AAIALQAAAE8ABwAHAAAAaQAAAB4AAAAeAAAA" ++
    "AQAAAAAAAAD5AAIALwAAAPgAAgAvAAAA9QATAAcAAADVAAAAHgAAAC4AAAA/AAAAJwAAAEUAAAAoAAAATgAAACkAAABXAAAAKgAA" ++
    "AF0AAAArAAAAZgAAACwAAABpAAAALQAAAEEABQAiAAAAbwAAAB8AAABuAAAAPQAEAAYAAABwAAAAbwAAALoABQByAAAAcwAAAHAA" ++
    "AABxAAAA9wADAHUAAAAAAAAA+gAEAHMAAAB0AAAAdQAAAPgAAgB0AAAAQQAGADgAAAB2AAAANgAAADcAAAAhAAAAPQAEAAYAAAB3" ++
    "AAAAdgAAAFEABQAGAAAAeQAAANUAAAABAAAAgwAFAAYAAAB6AAAAdwAAAHkAAABSAAYABwAAANQAAAB6AAAA1QAAAAEAAAD5AAIA" ++
    "dQAAAPgAAgB1AAAA9QAHAAcAAADWAAAA1QAAAC8AAADUAAAAdAAAAEEABQBBAAAAfgAAADYAAAA3AAAAPQAEAAcAAAB/AAAAfgAA" ++
    "AIgABQAHAAAAgAAAANYAAAB/AAAAPQAEAIQAAACHAAAAhgAAAFcABQANAAAAiQAAAIcAAACAAAAAQQAFADgAAACLAAAANgAAAIoA" ++
    "AAA9AAQABgAAAIwAAACLAAAAugAFAHIAAACNAAAAjAAAAHEAAAD3AAMAjwAAAAAAAAD6AAQAjQAAAI4AAACPAAAA+AACAI4AAABP" ++
    "AAkADQAAAJEAAACJAAAAiQAAAAIAAAABAAAAAAAAAAMAAAD5AAIAjwAAAPgAAgCPAAAA9QAHAA0AAADXAAAAiQAAAHUAAACRAAAA" ++
    "jgAAAEEABQAiAAAAkwAAAB8AAACSAAAAPQAEAAYAAACUAAAAkwAAAI4ABQANAAAAlgAAANcAAACUAAAAQQAFACIAAACXAAAAHwAA" ++
    "ADsAAAA9AAQABgAAAJgAAACXAAAAugAFAHIAAACaAAAAmAAAAJkAAAD3AAMAnAAAAAAAAAD6AAQAmgAAAJsAAACcAAAA+AACAJsA" ++
    "AAA9AAQADQAAAKAAAACfAAAATwAHAAcAAAChAAAAoAAAAKAAAAAAAAAAAQAAAFAABQAHAAAApAAAAJgAAACYAAAAgQAFAAcAAACl" ++
    "AAAAoQAAAKQAAABPAAcABwAAAKkAAACgAAAAoAAAAAIAAAADAAAAgQAFAAcAAACqAAAAoQAAAKkAAACDAAUABwAAAK4AAACqAAAA" ++
    "pAAAAAwACAAHAAAArwAAAAEAAAArAAAADAAAAKUAAACuAAAAgQAFAAYAAACzAAAAmAAAAHEAAAAMAAcABgAAALYAAAABAAAAQwAA" ++
    "AAwAAACvAAAAgwAFAAYAAAC3AAAAswAAALYAAAAMAAgABgAAALkAAAABAAAAKwAAALcAAACZAAAAuAAAAI4ABQANAAAAvAAAAJYA" ++
    "AAC5AAAA+QACAJwAAAD4AAIAnAAAAPUABwANAAAA2AAAAJYAAACPAAAAvAAAAJsAAAD3AAMAxAAAAAAAAAD6AAQAjQAAAMMAAADH" ++
    "AAAA+AACAMMAAABPAAkADQAAAMYAAADYAAAA2AAAAAIAAAABAAAAAAAAAAMAAAD5AAIAxAAAAPgAAgDHAAAA+QACAMQAAAD4AAIA" ++
    "xAAAAPUABwANAAAA2QAAAMYAAADDAAAA2AAAAMcAAAA+AAMAvgAAANkAAAD9AAEAOAABAA==");

// Adapted from SceneFX's MIT-licensed analytic rounded-box shadow shader.
pub const shadow_source =
    \\#version 450
    \\layout(push_constant) uniform Push {
    \\    vec2 target_size;
    \\    vec2 texture_size;
    \\    float swap_rb;
    \\} pc;
    \\layout(location=0) in vec2 pixel;
    \\layout(location=1) flat in vec4 dest;
    \\layout(location=3) flat in vec4 color;
    \\layout(location=4) flat in vec4 rounded;
    \\layout(location=5) flat in vec4 parameters;
    \\layout(location=0) out vec4 out_color;
    \\float gaussian(float value,float sigma) {
    \\    const float pi=3.141592653589793;
    \\    return exp(-(value*value)/(2.0*sigma*sigma))/(sqrt(2.0*pi)*sigma);
    \\}
    \\float erfApprox(float value) {
    \\    float s=sign(value),a=abs(value);
    \\    float denominator=1.0+(0.278393+(0.230389+0.078108*a*a)*a)*a;
    \\    denominator*=denominator;
    \\    return s-s/(denominator*denominator);
    \\}
    \\float roundedBoxShadowX(float x,float y,float sigma,float radius,vec2 half_size) {
    \\    float delta=min(half_size.y-radius-abs(y),0.0);
    \\    float curved=half_size.x-radius+sqrt(max(0.0,radius*radius-delta*delta));
    \\    vec2 integral=0.5+0.5*vec2(erfApprox((x-curved)*(sqrt(0.5)/sigma)),erfApprox((x+curved)*(sqrt(0.5)/sigma)));
    \\    return integral.y-integral.x;
    \\}
    \\float roundedBoxShadow(vec2 lower,vec2 upper,vec2 point,float sigma,float radius) {
    \\    vec2 center=(lower+upper)*0.5;
    \\    vec2 half_size=(upper-lower)*0.5;
    \\    point-=center;
    \\    float low=point.y-half_size.y;
    \\    float high=point.y+half_size.y;
    \\    float start=clamp(-3.0*sigma,low,high);
    \\    float end=clamp(3.0*sigma,low,high);
    \\    float step=(end-start)*0.25;
    \\    float y=start+step*0.5;
    \\    float coverage=0.0;
    \\    for (int i=0;i<4;i++) {
    \\        coverage+=roundedBoxShadowX(point.x,point.y-y,sigma,radius,half_size)*gaussian(y,sigma)*step;
    \\        y+=step;
    \\    }
    \\    return coverage;
    \\}
    \\float roundedRectCoverage(vec2 point,vec4 rect,float radius) {
    \\    vec2 q=abs(point-(rect.xy+rect.zw*0.5))-(rect.zw*0.5-vec2(radius));
    \\    float distance=length(max(q,vec2(0)))+min(max(q.x,q.y),0.0)-radius;
    \\    return clamp(0.5-distance,0.0,1.0);
    \\}
    \\void main() {
    \\    float cutout=parameters.w>0.5 ? 1.0-roundedRectCoverage(pixel,dest,parameters.z) : 1.0;
    \\    if (cutout<=0.0) discard;
    \\    float coverage=parameters.y>0.0 ? roundedBoxShadow(rounded.xy,rounded.xy+rounded.zw,pixel,parameters.y*0.5,parameters.x) : roundedRectCoverage(pixel,rounded,parameters.x);
    \\    vec4 shaded=color*coverage;
    \\    shaded*=cutout;
    \\    out_color=pc.swap_rb>0.5 ? shaded.bgra : shaded;
    \\}
;

pub const blur_horizontal_paired_source =
    \\#version 450
    \\layout(set=0,binding=0) uniform sampler2D tex;
    \\layout(push_constant) uniform Push {
    \\    vec2 target_size;
    \\    vec2 texture_size;
    \\    float swap_rb;
    \\} pc;
    \\layout(location=0) in vec2 pixel;
    \\layout(location=5) flat in vec4 parameters;
    \\layout(location=0) out vec4 out_color;
    \\void main() {
    \\    ivec2 coordinate=ivec2(pixel);
    \\    int radius=int(parameters.x);
    \\    int left=min(radius,coordinate.x);
    \\    int right=min(radius,int(pc.texture_size.x)-1-coordinate.x);
    \\    vec2 center=(vec2(coordinate)+vec2(0.5))/pc.texture_size;
    \\    vec4 sum=texelFetch(tex,coordinate,0);
    \\    for (int offset=1; offset<=left; offset+=2) {
    \\        if (offset<left) {
    \\            sum+=2.0*texture(tex,center-vec2(float(offset)+0.5,0.0)/pc.texture_size);
    \\        } else {
    \\            sum+=texelFetch(tex,coordinate-ivec2(offset,0),0);
    \\        }
    \\    }
    \\    for (int offset=1; offset<=right; offset+=2) {
    \\        if (offset<right) {
    \\            sum+=2.0*texture(tex,center+vec2(float(offset)+0.5,0.0)/pc.texture_size);
    \\        } else {
    \\            sum+=texelFetch(tex,coordinate+ivec2(offset,0),0);
    \\        }
    \\    }
    \\    out_color=sum/float(1+left+right);
    \\}
;

pub const blur_vertical_paired_source =
    \\#version 450
    \\layout(set=0,binding=0) uniform sampler2D tex;
    \\layout(push_constant) uniform Push {
    \\    vec2 target_size;
    \\    vec2 texture_size;
    \\    float swap_rb;
    \\} pc;
    \\layout(location=0) in vec2 pixel;
    \\layout(location=5) flat in vec4 parameters;
    \\layout(location=0) out vec4 out_color;
    \\void main() {
    \\    ivec2 coordinate=ivec2(pixel);
    \\    int radius=int(parameters.x);
    \\    int top=min(radius,coordinate.y);
    \\    int bottom=min(radius,int(pc.texture_size.y)-1-coordinate.y);
    \\    vec2 center=(vec2(coordinate)+vec2(0.5))/pc.texture_size;
    \\    vec4 sum=texelFetch(tex,coordinate,0);
    \\    for (int offset=1; offset<=top; offset+=2) {
    \\        if (offset<top) {
    \\            sum+=2.0*texture(tex,center-vec2(0.0,float(offset)+0.5)/pc.texture_size);
    \\        } else {
    \\            sum+=texelFetch(tex,coordinate-ivec2(0,offset),0);
    \\        }
    \\    }
    \\    for (int offset=1; offset<=bottom; offset+=2) {
    \\        if (offset<bottom) {
    \\            sum+=2.0*texture(tex,center+vec2(0.0,float(offset)+0.5)/pc.texture_size);
    \\        } else {
    \\            sum+=texelFetch(tex,coordinate+ivec2(0,offset),0);
    \\        }
    \\    }
    \\    out_color=sum/float(1+top+bottom);
    \\}
;

pub const quad = decodeSpirv(
    "AwIjBwAAAQALAA0ATwAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ACQAAAAAABAAA" ++
        "AG1haW4AAAAADAAAACsAAAA+AAAATAAAAEcABAAMAAAACwAAACoAAABHAAMAGAAAAAIAAABIAAUAGAAAAAAAAAAjAAAAAAAAAEgA" ++
        "BQAYAAAAAQAAACMAAAAQAAAASAAFABgAAAACAAAAIwAAACAAAABIAAUAGAAAAAMAAAAjAAAAKAAAAEgABQAYAAAABAAAACMAAAAw" ++
        "AAAASAAFABgAAAAFAAAAIwAAAEAAAABIAAUAGAAAAAYAAAAjAAAAUAAAAEgABQAYAAAABwAAACMAAABUAAAASAAFABgAAAAIAAAA" ++
        "IwAAAFgAAABHAAMAKQAAAAIAAABIAAUAKQAAAAAAAAALAAAAAAAAAEgABQApAAAAAQAAAAsAAAABAAAASAAFACkAAAACAAAACwAA" ++
        "AAMAAABIAAUAKQAAAAMAAAALAAAABAAAAEcABAA+AAAAHgAAAAAAAABHAAQATAAAAB4AAAABAAAAEwACAAIAAAAhAAMAAwAAAAIA" ++
        "AAAWAAMABgAAACAAAAAXAAQABwAAAAYAAAACAAAAFQAEAAoAAAAgAAAAAQAAACAABAALAAAAAQAAAAoAAAA7AAQACwAAAAwAAAAB" ++
        "AAAAKwAEAAoAAAAOAAAAAQAAABcABAAXAAAABgAAAAQAAAAeAAsAGAAAABcAAAAXAAAABwAAAAcAAAAXAAAAFwAAAAYAAAAGAAAA" ++
        "BgAAACAABAAZAAAACQAAABgAAAA7AAQAGQAAABoAAAAJAAAAKwAEAAoAAAAbAAAAAAAAACAABAAcAAAACQAAABcAAAAVAAQAJgAA" ++
        "ACAAAAAAAAAAKwAEACYAAAAnAAAAAQAAABwABAAoAAAABgAAACcAAAAeAAYAKQAAABcAAAAGAAAAKAAAACgAAAAgAAQAKgAAAAMA" ++
        "AAApAAAAOwAEACoAAAArAAAAAwAAACsABAAKAAAALQAAAAIAAAAgAAQALgAAAAkAAAAHAAAAKwAEAAYAAAAyAAAAAAAAQCsABAAG" ++
        "AAAANAAAAAAAgD8rAAQABgAAADcAAAAAAAAAIAAEADsAAAADAAAAFwAAACAABAA9AAAAAwAAAAcAAAA7AAQAPQAAAD4AAAADAAAA" ++
        "KwAEAAoAAABIAAAAAwAAADsABAA9AAAATAAAAAMAAAAsAAUABwAAAE4AAAA0AAAANAAAADYABQACAAAABAAAAAAAAAADAAAA+AAC" ++
        "AAUAAAA9AAQACgAAAA0AAAAMAAAAxwAFAAoAAAAPAAAADQAAAA4AAABvAAQABgAAABAAAAAPAAAAwwAFAAoAAAASAAAADQAAAA4A" ++
        "AADHAAUACgAAABMAAAASAAAADgAAAG8ABAAGAAAAFAAAABMAAABQAAUABwAAABUAAAAQAAAAFAAAAEEABQAcAAAAHQAAABoAAAAb" ++
        "AAAAPQAEABcAAAAeAAAAHQAAAE8ABwAHAAAAHwAAAB4AAAAeAAAAAAAAAAEAAABPAAcABwAAACMAAAAeAAAAHgAAAAIAAAADAAAA" ++
        "hQAFAAcAAAAkAAAAFQAAACMAAACBAAUABwAAACUAAAAfAAAAJAAAAEEABQAuAAAALwAAABoAAAAtAAAAPQAEAAcAAAAwAAAALwAA" ++
        "AIgABQAHAAAAMQAAACUAAAAwAAAAjgAFAAcAAAAzAAAAMQAAADIAAACDAAUABwAAADYAAAAzAAAATgAAAFEABQAGAAAAOAAAADYA" ++
        "AAAAAAAAUQAFAAYAAAA5AAAANgAAAAEAAABQAAcAFwAAADoAAAA4AAAAOQAAADcAAAA0AAAAQQAFADsAAAA8AAAAKwAAABsAAAA+" ++
        "AAMAPAAAADoAAABBAAUAHAAAAD8AAAAaAAAADgAAAD0ABAAXAAAAQAAAAD8AAABPAAcABwAAAEEAAABAAAAAQAAAAAAAAAABAAAA" ++
        "TwAHAAcAAABFAAAAQAAAAEAAAAACAAAAAwAAAIUABQAHAAAARgAAABUAAABFAAAAgQAFAAcAAABHAAAAQQAAAEYAAABBAAUALgAA" ++
        "AEkAAAAaAAAASAAAAD0ABAAHAAAASgAAAEkAAACIAAUABwAAAEsAAABHAAAASgAAAD4AAwA+AAAASwAAAD4AAwBMAAAAJQAAAP0A" ++
        "AQA4AAEA",
);

pub const solid = decodeSpirv(
    "AwIjBwAAAQALAA0AJAAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ABgAEAAAABAAA" ++
        "AG1haW4AAAAACQAAABAAAwAEAAAABwAAAEcABAAJAAAAHgAAAAAAAABHAAMACwAAAAIAAABIAAUACwAAAAAAAAAjAAAAAAAAAEgA" ++
        "BQALAAAAAQAAACMAAAAQAAAASAAFAAsAAAACAAAAIwAAACAAAABIAAUACwAAAAMAAAAjAAAAKAAAAEgABQALAAAABAAAACMAAAAw" ++
        "AAAASAAFAAsAAAAFAAAAIwAAAEAAAABIAAUACwAAAAYAAAAjAAAAUAAAAEgABQALAAAABwAAACMAAABUAAAASAAFAAsAAAAIAAAA" ++
        "IwAAAFgAAAATAAIAAgAAACEAAwADAAAAAgAAABYAAwAGAAAAIAAAABcABAAHAAAABgAAAAQAAAAgAAQACAAAAAMAAAAHAAAAOwAE" ++
        "AAgAAAAJAAAAAwAAABcABAAKAAAABgAAAAIAAAAeAAsACwAAAAcAAAAHAAAACgAAAAoAAAAHAAAABwAAAAYAAAAGAAAABgAAACAA" ++
        "BAAMAAAACQAAAAsAAAA7AAQADAAAAA0AAAAJAAAAFQAEAA4AAAAgAAAAAQAAACsABAAOAAAADwAAAAgAAAAgAAQAEAAAAAkAAAAG" ++
        "AAAAKwAEAAYAAAATAAAAAAAAPxQAAgAUAAAAKwAEAA4AAAAaAAAABAAAACAABAAbAAAACQAAAAcAAAA2AAUAAgAAAAQAAAAAAAAA" ++
        "AwAAAPgAAgAFAAAAQQAFABAAAAARAAAADQAAAA8AAAA9AAQABgAAABIAAAARAAAAugAFABQAAAAVAAAAEgAAABMAAAD3AAMAGQAA" ++
        "AAAAAAD6AAQAFQAAABgAAAAfAAAA+AACABgAAABBAAUAGwAAABwAAAANAAAAGgAAAD0ABAAHAAAAHQAAABwAAABPAAkABwAAAB4A" ++
        "AAAdAAAAHQAAAAIAAAABAAAAAAAAAAMAAAD5AAIAGQAAAPgAAgAfAAAAQQAFABsAAAAgAAAADQAAABoAAAA9AAQABwAAACEAAAAg" ++
        "AAAA+QACABkAAAD4AAIAGQAAAPUABwAHAAAAIwAAAB4AAAAYAAAAIQAAAB8AAAA+AAMACQAAACMAAAD9AAEAOAABAA==",
);

pub const image = decodeSpirv(
    "AwIjBwAAAQALAA0AYQAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ACAAEAAAABAAA" ++
        "AG1haW4AAAAAEQAAACwAAABSAAAAEAADAAQAAAAHAAAARwAEAA0AAAAhAAAAAAAAAEcABAANAAAAIgAAAAAAAABHAAQAEQAAAB4A" ++
        "AAAAAAAARwADABQAAAACAAAASAAFABQAAAAAAAAAIwAAAAAAAABIAAUAFAAAAAEAAAAjAAAAEAAAAEgABQAUAAAAAgAAACMAAAAg" ++
        "AAAASAAFABQAAAADAAAAIwAAACgAAABIAAUAFAAAAAQAAAAjAAAAMAAAAEgABQAUAAAABQAAACMAAABAAAAASAAFABQAAAAGAAAA" ++
        "IwAAAFAAAABIAAUAFAAAAAcAAAAjAAAAVAAAAEgABQAUAAAACAAAACMAAABYAAAARwAEACwAAAAeAAAAAQAAAEcABABSAAAAHgAA" ++
        "AAAAAAATAAIAAgAAACEAAwADAAAAAgAAABYAAwAGAAAAIAAAABcABAAHAAAABgAAAAQAAAAZAAkACgAAAAYAAAABAAAAAAAAAAAA" ++
        "AAAAAAAAAQAAAAAAAAAbAAMACwAAAAoAAAAgAAQADAAAAAAAAAALAAAAOwAEAAwAAAANAAAAAAAAABcABAAPAAAABgAAAAIAAAAg" ++
        "AAQAEAAAAAEAAAAPAAAAOwAEABAAAAARAAAAAQAAAB4ACwAUAAAABwAAAAcAAAAPAAAADwAAAAcAAAAHAAAABgAAAAYAAAAGAAAA" ++
        "IAAEABUAAAAJAAAAFAAAADsABAAVAAAAFgAAAAkAAAAVAAQAFwAAACAAAAABAAAAKwAEABcAAAAYAAAACAAAACAABAAZAAAACQAA" ++
        "AAYAAAArAAQABgAAABwAAAAAAAA/FAACAB0AAAArAAQAFwAAACMAAAAGAAAAKwAEAAYAAAAmAAAAAAAAADsABAAQAAAALAAAAAEA" ++
        "AAArAAQAFwAAAC4AAAAFAAAAIAAEAC8AAAAJAAAABwAAACsABAAGAAAATAAAAAAAgD8gAAQAUQAAAAMAAAAHAAAAOwAEAFEAAABS" ++
        "AAAAAwAAADYABQACAAAABAAAAAAAAAADAAAA+AACAAUAAAA9AAQACwAAAA4AAAANAAAAPQAEAA8AAAASAAAAEQAAAFcABQAHAAAA" ++
        "EwAAAA4AAAASAAAAQQAFABkAAAAaAAAAFgAAABgAAAA9AAQABgAAABsAAAAaAAAAugAFAB0AAAAeAAAAGwAAABwAAAD3AAMAIAAA" ++
        "AAAAAAD6AAQAHgAAAB8AAAAgAAAA+AACAB8AAABPAAkABwAAACIAAAATAAAAEwAAAAIAAAABAAAAAAAAAAMAAAD5AAIAIAAAAPgA" ++
        "AgAgAAAA9QAHAAcAAABeAAAAEwAAAAUAAAAiAAAAHwAAAEEABQAZAAAAJAAAABYAAAAjAAAAPQAEAAYAAAAlAAAAJAAAALoABQAd" ++
        "AAAAJwAAACUAAAAmAAAA9wADACkAAAAAAAAA+gAEACcAAAAoAAAAKQAAAPgAAgAoAAAAPQAEAA8AAAAtAAAALAAAAEEABQAvAAAA" ++
        "MAAAABYAAAAuAAAAPQAEAAcAAAAxAAAAMAAAAE8ABwAPAAAAMgAAADEAAAAxAAAAAAAAAAEAAABQAAUADwAAADUAAAAlAAAAJQAA" ++
        "AIEABQAPAAAANgAAADIAAAA1AAAATwAHAA8AAAA8AAAAMQAAADEAAAACAAAAAwAAAIEABQAPAAAAPQAAADIAAAA8AAAAgwAFAA8A" ++
        "AABBAAAAPQAAADUAAAAMAAgADwAAAEIAAAABAAAAKwAAAC0AAAA2AAAAQQAAAIEABQAGAAAARwAAACUAAAAcAAAADAAHAAYAAABK" ++
        "AAAAAQAAAEMAAAAtAAAAQgAAAIMABQAGAAAASwAAAEcAAABKAAAADAAIAAYAAABNAAAAAQAAACsAAABLAAAAJgAAAEwAAACOAAUA" ++
        "BwAAAFAAAABeAAAATQAAAPkAAgApAAAA+AACACkAAAD1AAcABwAAAF8AAABeAAAAIAAAAFAAAAAoAAAA9wADAFgAAAAAAAAA+gAE" ++
        "AB4AAABXAAAAWwAAAPgAAgBXAAAATwAJAAcAAABaAAAAXwAAAF8AAAACAAAAAQAAAAAAAAADAAAA+QACAFgAAAD4AAIAWwAAAPkA" ++
        "AgBYAAAA+AACAFgAAAD1AAcABwAAAGAAAABaAAAAVwAAAF8AAABbAAAAPgADAFIAAABgAAAA/QABADgAAQA=",
);

pub const shadow = decodeSpirv(
    "AwIjBwAAAQALAA0AbgAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ABwAEAAAABAAA" ++
        "AG1haW4AAAAACwAAAF0AAAAQAAMABAAAAAcAAABHAAQACwAAAB4AAAABAAAARwADAA4AAAACAAAASAAFAA4AAAAAAAAAIwAAAAAA" ++
        "AABIAAUADgAAAAEAAAAjAAAAEAAAAEgABQAOAAAAAgAAACMAAAAgAAAASAAFAA4AAAADAAAAIwAAACgAAABIAAUADgAAAAQAAAAj" ++
        "AAAAMAAAAEgABQAOAAAABQAAACMAAABAAAAASAAFAA4AAAAGAAAAIwAAAFAAAABIAAUADgAAAAcAAAAjAAAAVAAAAEgABQAOAAAA" ++
        "CAAAACMAAABYAAAARwAEAF0AAAAeAAAAAAAAABMAAgACAAAAIQADAAMAAAACAAAAFgADAAYAAAAgAAAAFwAEAAcAAAAGAAAAAgAA" ++
        "ACAABAAKAAAAAQAAAAcAAAA7AAQACgAAAAsAAAABAAAAFwAEAA0AAAAGAAAABAAAAB4ACwAOAAAADQAAAA0AAAAHAAAABwAAAA0A" ++
        "AAANAAAABgAAAAYAAAAGAAAAIAAEAA8AAAAJAAAADgAAADsABAAPAAAAEAAAAAkAAAAVAAQAEQAAACAAAAABAAAAKwAEABEAAAAS" ++
        "AAAABQAAACAABAATAAAACQAAAA0AAAArAAQABgAAABoAAAAAAAA/KwAEABEAAAAjAAAABgAAACAABAAkAAAACQAAAAYAAAArAAQA" ++
        "BgAAAC0AAAAAAAAALAAFAAcAAAAuAAAALQAAAC0AAAArAAQAEQAAAD8AAAAHAAAAFAACAEIAAAArAAQABgAAAEgAAAAAAABAKwAE" ++
        "AAYAAABOAAAAAACAPysABAARAAAAVwAAAAQAAAAgAAQAXAAAAAMAAAANAAAAOwAEAFwAAABdAAAAAwAAACsABAARAAAAXgAAAAgA" ++
        "AAA2AAUAAgAAAAQAAAAAAAAAAwAAAPgAAgAFAAAAPQAEAAcAAAAMAAAACwAAAEEABQATAAAAFAAAABAAAAASAAAAPQAEAA0AAAAV" ++
        "AAAAFAAAAE8ABwAHAAAAFgAAABUAAAAVAAAAAAAAAAEAAABPAAcABwAAABkAAAAVAAAAFQAAAAIAAAADAAAAjgAFAAcAAAAbAAAA" ++
        "GQAAABoAAACBAAUABwAAABwAAAAWAAAAGwAAAIMABQAHAAAAHQAAAAwAAAAcAAAADAAGAAcAAAAeAAAAAQAAAAQAAAAdAAAAQQAF" ++
        "ACQAAAAlAAAAEAAAACMAAAA9AAQABgAAACYAAAAlAAAAUAAFAAcAAAAnAAAAJgAAACYAAACDAAUABwAAACgAAAAbAAAAJwAAAIMA" ++
        "BQAHAAAAKQAAAB4AAAAoAAAADAAHAAcAAAAvAAAAAQAAACgAAAApAAAALgAAAAwABgAGAAAAMAAAAAEAAABCAAAALwAAAFEABQAG" ++
        "AAAANAAAACkAAAAAAAAAUQAFAAYAAAA3AAAAKQAAAAEAAAAMAAcABgAAADgAAAABAAAAKAAAADQAAAA3AAAADAAHAAYAAAA5AAAA" ++
        "AQAAACUAAAA4AAAALQAAAIEABQAGAAAAOgAAADAAAAA5AAAAgwAFAAYAAAA9AAAAOgAAACYAAABBAAUAJAAAAEAAAAAQAAAAPwAA" ++
        "AD0ABAAGAAAAQQAAAEAAAAC6AAUAQgAAAEMAAABBAAAALQAAAPcAAwBGAAAAAAAAAPoABABDAAAARQAAAFAAAAD4AAIARQAAAIUA" ++
        "BQAGAAAASwAAAEgAAABBAAAAiAAFAAYAAABMAAAAPQAAAEsAAACDAAUABgAAAE0AAAAaAAAATAAAAAwACAAGAAAATwAAAAEAAAAr" ++
        "AAAATQAAAC0AAABOAAAA+QACAEYAAAD4AAIAUAAAAIMABQAGAAAAUgAAABoAAAA9AAAADAAIAAYAAABTAAAAAQAAACsAAABSAAAA" ++
        "LQAAAE4AAAD5AAIARgAAAPgAAgBGAAAA9QAHAAYAAABsAAAATwAAAEUAAABTAAAAUAAAAEEABQATAAAAWAAAABAAAABXAAAAPQAE" ++
        "AA0AAABZAAAAWAAAAI4ABQANAAAAWwAAAFkAAABsAAAAQQAFACQAAABfAAAAEAAAAF4AAAA9AAQABgAAAGAAAABfAAAAugAFAEIA" ++
        "AABhAAAAYAAAABoAAAD3AAMAZAAAAAAAAAD6AAQAYQAAAGMAAABnAAAA+AACAGMAAABPAAkADQAAAGYAAABbAAAAWwAAAAIAAAAB" ++
        "AAAAAAAAAAMAAAD5AAIAZAAAAPgAAgBnAAAA+QACAGQAAAD4AAIAZAAAAPUABwANAAAAbQAAAGYAAABjAAAAWwAAAGcAAAA+AAMA" ++
        "XQAAAG0AAAD9AAEAOAABAA==",
);

pub const quad_instanced = decodeSpirv(
    "AwIjBwAAAQALAA0ATgAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8AEwAAAAAABAAA" ++
        "AG1haW4AAAAADAAAABkAAAAmAAAAPAAAAD4AAAA/AAAAQQAAAEIAAABEAAAARQAAAEcAAABIAAAASgAAAEsAAABHAAQADAAAAAsA" ++
        "AAAqAAAARwAEABkAAAAeAAAAAgAAAEcAAwAkAAAAAgAAAEgABQAkAAAAAAAAAAsAAAAAAAAASAAFACQAAAABAAAACwAAAAEAAABI" ++
        "AAUAJAAAAAIAAAALAAAAAwAAAEgABQAkAAAAAwAAAAsAAAAEAAAARwADACkAAAACAAAASAAFACkAAAAAAAAAIwAAAAAAAABIAAUA" ++
        "KQAAAAEAAAAjAAAACAAAAEgABQApAAAAAgAAACMAAAAQAAAARwAEADwAAAAeAAAAAAAAAEcAAwA+AAAADgAAAEcABAA+AAAAHgAA" ++
        "AAEAAABHAAQAPwAAAB4AAAAAAAAARwADAEEAAAAOAAAARwAEAEEAAAAeAAAAAgAAAEcABABCAAAAHgAAAAEAAABHAAMARAAAAA4A" ++
        "AABHAAQARAAAAB4AAAADAAAARwAEAEUAAAAeAAAAAwAAAEcAAwBHAAAADgAAAEcABABHAAAAHgAAAAQAAABHAAQASAAAAB4AAAAE" ++
        "AAAARwADAEoAAAAOAAAARwAEAEoAAAAeAAAABQAAAEcABABLAAAAHgAAAAUAAAATAAIAAgAAACEAAwADAAAAAgAAABYAAwAGAAAA" ++
        "IAAAABcABAAHAAAABgAAAAIAAAAVAAQACgAAACAAAAABAAAAIAAEAAsAAAABAAAACgAAADsABAALAAAADAAAAAEAAAArAAQACgAA" ++
        "AA4AAAABAAAAFwAEABcAAAAGAAAABAAAACAABAAYAAAAAQAAABcAAAA7AAQAGAAAABkAAAABAAAAFQAEACEAAAAgAAAAAAAAACsA" ++
        "BAAhAAAAIgAAAAEAAAAcAAQAIwAAAAYAAAAiAAAAHgAGACQAAAAXAAAABgAAACMAAAAjAAAAIAAEACUAAAADAAAAJAAAADsABAAl" ++
        "AAAAJgAAAAMAAAArAAQACgAAACcAAAAAAAAAHgAFACkAAAAHAAAABwAAAAYAAAAgAAQAKgAAAAkAAAApAAAAOwAEACoAAAArAAAA" ++
        "CQAAACAABAAsAAAACQAAAAcAAAArAAQABgAAADAAAAAAAABAKwAEAAYAAAAyAAAAAACAPysABAAGAAAANQAAAAAAAAAgAAQAOQAA" ++
        "AAMAAAAXAAAAIAAEADsAAAADAAAABwAAADsABAA7AAAAPAAAAAMAAAA7AAQAOQAAAD4AAAADAAAAOwAEABgAAAA/AAAAAQAAADsA" ++
        "BAA5AAAAQQAAAAMAAAA7AAQAGAAAAEIAAAABAAAAOwAEADkAAABEAAAAAwAAADsABAAYAAAARQAAAAEAAAA7AAQAOQAAAEcAAAAD" ++
        "AAAAOwAEABgAAABIAAAAAQAAADsABAA5AAAASgAAAAMAAAA7AAQAGAAAAEsAAAABAAAALAAFAAcAAABNAAAAMgAAADIAAAA2AAUA" ++
        "AgAAAAQAAAAAAAAAAwAAAPgAAgAFAAAAPQAEAAoAAAANAAAADAAAAMcABQAKAAAADwAAAA0AAAAOAAAAbwAEAAYAAAAQAAAADwAA" ++
        "AMMABQAKAAAAEgAAAA0AAAAOAAAAxwAFAAoAAAATAAAAEgAAAA4AAABvAAQABgAAABQAAAATAAAAUAAFAAcAAAAVAAAAEAAAABQA" ++
        "AAA9AAQAFwAAABoAAAAZAAAATwAHAAcAAAAbAAAAGgAAABoAAAAAAAAAAQAAAE8ABwAHAAAAHgAAABoAAAAaAAAAAgAAAAMAAACF" ++
        "AAUABwAAAB8AAAAVAAAAHgAAAIEABQAHAAAAIAAAABsAAAAfAAAAQQAFACwAAAAtAAAAKwAAACcAAAA9AAQABwAAAC4AAAAtAAAA" ++
        "iAAFAAcAAAAvAAAAIAAAAC4AAACOAAUABwAAADEAAAAvAAAAMAAAAIMABQAHAAAANAAAADEAAABNAAAAUQAFAAYAAAA2AAAANAAA" ++
        "AAAAAABRAAUABgAAADcAAAA0AAAAAQAAAFAABwAXAAAAOAAAADYAAAA3AAAANQAAADIAAABBAAUAOQAAADoAAAAmAAAAJwAAAD4A" ++
        "AwA6AAAAOAAAAD4AAwA8AAAAIAAAAD0ABAAXAAAAQAAAAD8AAAA+AAMAPgAAAEAAAAA9AAQAFwAAAEMAAABCAAAAPgADAEEAAABD" ++
        "AAAAPQAEABcAAABGAAAARQAAAD4AAwBEAAAARgAAAD0ABAAXAAAASQAAAEgAAAA+AAMARwAAAEkAAAA9AAQAFwAAAEwAAABLAAAA" ++
        "PgADAEoAAABMAAAA/QABADgAAQA=",
);

pub const solid_instanced = decodeSpirv(
    "AwIjBwAAAQALAA0AIgAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ABwAEAAAABAAA" ++
        "AG1haW4AAAAACQAAABsAAAAQAAMABAAAAAcAAABHAAQACQAAAB4AAAAAAAAARwADAAsAAAACAAAASAAFAAsAAAAAAAAAIwAAAAAA" ++
        "AABIAAUACwAAAAEAAAAjAAAACAAAAEgABQALAAAAAgAAACMAAAAQAAAARwADABsAAAAOAAAARwAEABsAAAAeAAAAAwAAABMAAgAC" ++
        "AAAAIQADAAMAAAACAAAAFgADAAYAAAAgAAAAFwAEAAcAAAAGAAAABAAAACAABAAIAAAAAwAAAAcAAAA7AAQACAAAAAkAAAADAAAA" ++
        "FwAEAAoAAAAGAAAAAgAAAB4ABQALAAAACgAAAAoAAAAGAAAAIAAEAAwAAAAJAAAACwAAADsABAAMAAAADQAAAAkAAAAVAAQADgAA" ++
        "ACAAAAABAAAAKwAEAA4AAAAPAAAAAgAAACAABAAQAAAACQAAAAYAAAArAAQABgAAABMAAAAAAAA/FAACABQAAAAgAAQAGgAAAAEA" ++
        "AAAHAAAAOwAEABoAAAAbAAAAAQAAADYABQACAAAABAAAAAAAAAADAAAA+AACAAUAAABBAAUAEAAAABEAAAANAAAADwAAAD0ABAAG" ++
        "AAAAEgAAABEAAAC6AAUAFAAAABUAAAASAAAAEwAAAPcAAwAZAAAAAAAAAPoABAAVAAAAGAAAAB4AAAD4AAIAGAAAAD0ABAAHAAAA" ++
        "HAAAABsAAABPAAkABwAAAB0AAAAcAAAAHAAAAAIAAAABAAAAAAAAAAMAAAD5AAIAGQAAAPgAAgAeAAAAPQAEAAcAAAAfAAAAGwAA" ++
        "APkAAgAZAAAA+AACABkAAAD1AAcABwAAACEAAAAdAAAAGAAAAB8AAAAeAAAAPgADAAkAAAAhAAAA/QABADgAAQA=",
);

pub const image_instanced = decodeSpirv(
    "AwIjBwAAAQALAA0A1QAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ACwAEAAAABAAA" ++
        "AG1haW4AAAAACwAAAA8AAAAXAAAAHwAAAJoAAAC5AAAAEAADAAQAAAAHAAAARwAEAAsAAAAeAAAAAAAAAEcAAwAPAAAADgAAAEcA" ++
        "BAAPAAAAHgAAAAEAAABHAAMAFwAAAA4AAABHAAQAFwAAAB4AAAACAAAARwADAB8AAAAOAAAARwAEAB8AAAAeAAAABQAAAEcAAwA0" ++
        "AAAAAgAAAEgABQA0AAAAAAAAACMAAAAAAAAASAAFADQAAAABAAAAIwAAAAgAAABIAAUANAAAAAIAAAAjAAAAEAAAAEcABACGAAAA" ++
        "IQAAAAAAAABHAAQAhgAAACIAAAAAAAAARwADAJoAAAAOAAAARwAEAJoAAAAeAAAABAAAAEcABAC5AAAAHgAAAAAAAAATAAIAAgAA" ++
        "ACEAAwADAAAAAgAAABYAAwAGAAAAIAAAABcABAAHAAAABgAAAAIAAAAgAAQACgAAAAEAAAAHAAAAOwAEAAoAAAALAAAAAQAAABcA" ++
        "BAANAAAABgAAAAQAAAAgAAQADgAAAAEAAAANAAAAOwAEAA4AAAAPAAAAAQAAADsABAAOAAAAFwAAAAEAAAA7AAQADgAAAB8AAAAB" ++
        "AAAAFQAEACAAAAAgAAAAAAAAACsABAAgAAAAIQAAAAEAAAAgAAQAIgAAAAEAAAAGAAAAFQAEACUAAAAgAAAAAQAAAB4ABQA0AAAA" ++
        "BwAAAAcAAAAGAAAAIAAEADUAAAAJAAAANAAAADsABAA1AAAANgAAAAkAAAArAAQAJQAAADcAAAABAAAAIAAEADgAAAAJAAAABgAA" ++
        "ACsABAAgAAAAOwAAAAAAAAAgAAQAQQAAAAkAAAAHAAAAKwAEACAAAABuAAAAAgAAACsABAAGAAAAcQAAAAAAAD8UAAIAcgAAABkA" ++
        "CQCDAAAABgAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAABsAAwCEAAAAgwAAACAABACFAAAAAAAAAIQAAAA7AAQAhQAAAIYAAAAA" ++
        "AAAAKwAEACUAAACKAAAAAgAAACsABAAGAAAAlAAAAAAAAAA7AAQADgAAAJoAAAABAAAAKwAEAAYAAACzAAAAAACAPyAABAC4AAAA" ++
        "AwAAAA0AAAA7AAQAuAAAALkAAAADAAAANgAFAAIAAAAEAAAAAAAAAAMAAAD4AAIABQAAAD0ABAAHAAAADAAAAAsAAAA9AAQADQAA" ++
        "ABAAAAAPAAAATwAHAAcAAAARAAAAEAAAABAAAAAAAAAAAQAAAIMABQAHAAAAEgAAAAwAAAARAAAATwAHAAcAAAAUAAAAEAAAABAA" ++
        "AAACAAAAAwAAAIgABQAHAAAAFQAAABIAAAAUAAAAPQAEAA0AAAAYAAAAFwAAAE8ABwAHAAAAGQAAABgAAAAYAAAAAAAAAAEAAABP" ++
        "AAcABwAAABwAAAAYAAAAGAAAAAIAAAADAAAAhQAFAAcAAAAdAAAAFQAAABwAAACBAAUABwAAAB4AAAAZAAAAHQAAAEEABQAiAAAA" ++
        "IwAAAB8AAAAhAAAAPQAEAAYAAAAkAAAAIwAAAG4ABAAlAAAAJgAAACQAAAD3AAMALwAAAAAAAAD7ABEAJgAAAC4AAAABAAAAJwAA" ++
        "AAIAAAAoAAAAAwAAACkAAAAEAAAAKgAAAAUAAAArAAAABgAAACwAAAAHAAAALQAAAPgAAgAuAAAA+QACAC8AAAD4AAIAJwAAAFEA" ++
        "BQAGAAAAMwAAAB4AAAABAAAAQQAGADgAAAA5AAAANgAAADcAAAAhAAAAPQAEAAYAAAA6AAAAOQAAAFEABQAGAAAAPQAAAB4AAAAA" ++
        "AAAAgwAFAAYAAAA+AAAAOgAAAD0AAABQAAUABwAAAD8AAAAzAAAAPgAAAPkAAgAvAAAA+AACACgAAABBAAUAQQAAAEIAAAA2AAAA" ++
        "NwAAAD0ABAAHAAAAQwAAAEIAAACDAAUABwAAAEUAAABDAAAAHgAAAPkAAgAvAAAA+AACACkAAABBAAYAOAAAAEcAAAA2AAAANwAA" ++
        "ADsAAAA9AAQABgAAAEgAAABHAAAAUQAFAAYAAABKAAAAHgAAAAEAAACDAAUABgAAAEsAAABIAAAASgAAAFEABQAGAAAATQAAAB4A" ++
        "AAAAAAAAUAAFAAcAAABOAAAASwAAAE0AAAD5AAIALwAAAPgAAgAqAAAAQQAGADgAAABQAAAANgAAADcAAAA7AAAAPQAEAAYAAABR" ++
        "AAAAUAAAAFEABQAGAAAAUwAAAB4AAAAAAAAAgwAFAAYAAABUAAAAUQAAAFMAAABRAAUABgAAAFYAAAAeAAAAAQAAAFAABQAHAAAA" ++
        "VwAAAFQAAABWAAAA+QACAC8AAAD4AAIAKwAAAEEABQBBAAAAWQAAADYAAAA3AAAAPQAEAAcAAABaAAAAWQAAAE8ABwAHAAAAXAAA" ++
        "AB4AAAAeAAAAAQAAAAAAAACDAAUABwAAAF0AAABaAAAAXAAAAPkAAgAvAAAA+AACACwAAABRAAUABgAAAGAAAAAeAAAAAAAAAEEA" ++
        "BgA4AAAAYQAAADYAAAA3AAAAIQAAAD0ABAAGAAAAYgAAAGEAAABRAAUABgAAAGQAAAAeAAAAAQAAAIMABQAGAAAAZQAAAGIAAABk" ++
        "AAAAUAAFAAcAAABmAAAAYAAAAGUAAAD5AAIALwAAAPgAAgAtAAAATwAHAAcAAABpAAAAHgAAAB4AAAABAAAAAAAAAPkAAgAvAAAA" ++
        "+AACAC8AAAD1ABMABwAAANAAAAAeAAAALgAAAD8AAAAnAAAARQAAACgAAABOAAAAKQAAAFcAAAAqAAAAXQAAACsAAABmAAAALAAA" ++
        "AGkAAAAtAAAAQQAFACIAAABvAAAAHwAAAG4AAAA9AAQABgAAAHAAAABvAAAAugAFAHIAAABzAAAAcAAAAHEAAAD3AAMAdQAAAAAA" ++
        "AAD6AAQAcwAAAHQAAAB1AAAA+AACAHQAAABBAAYAOAAAAHYAAAA2AAAANwAAACEAAAA9AAQABgAAAHcAAAB2AAAAUQAFAAYAAAB5" ++
        "AAAA0AAAAAEAAACDAAUABgAAAHoAAAB3AAAAeQAAAFIABgAHAAAAzwAAAHoAAADQAAAAAQAAAPkAAgB1AAAA+AACAHUAAAD1AAcA" ++
        "BwAAANEAAADQAAAALwAAAM8AAAB0AAAAQQAFAEEAAAB+AAAANgAAADcAAAA9AAQABwAAAH8AAAB+AAAAiAAFAAcAAACAAAAA0QAA" ++
        "AH8AAAA9AAQAhAAAAIcAAACGAAAAVwAFAA0AAACJAAAAhwAAAIAAAABBAAUAOAAAAIsAAAA2AAAAigAAAD0ABAAGAAAAjAAAAIsA" ++
        "AAC6AAUAcgAAAI0AAACMAAAAcQAAAPcAAwCPAAAAAAAAAPoABACNAAAAjgAAAI8AAAD4AAIAjgAAAE8ACQANAAAAkQAAAIkAAACJ" ++
        "AAAAAgAAAAEAAAAAAAAAAwAAAPkAAgCPAAAA+AACAI8AAAD1AAcADQAAANIAAACJAAAAdQAAAJEAAACOAAAAQQAFACIAAACSAAAA" ++
        "HwAAADsAAAA9AAQABgAAAJMAAACSAAAAugAFAHIAAACVAAAAkwAAAJQAAAD3AAMAlwAAAAAAAAD6AAQAlQAAAJYAAACXAAAA+AAC" ++
        "AJYAAAA9AAQADQAAAJsAAACaAAAATwAHAAcAAACcAAAAmwAAAJsAAAAAAAAAAQAAAFAABQAHAAAAnwAAAJMAAACTAAAAgQAFAAcA" ++
        "AACgAAAAnAAAAJ8AAABPAAcABwAAAKQAAACbAAAAmwAAAAIAAAADAAAAgQAFAAcAAAClAAAAnAAAAKQAAACDAAUABwAAAKkAAACl" ++
        "AAAAnwAAAAwACAAHAAAAqgAAAAEAAAArAAAADAAAAKAAAACpAAAAgQAFAAYAAACuAAAAkwAAAHEAAAAMAAcABgAAALEAAAABAAAA" ++
        "QwAAAAwAAACqAAAAgwAFAAYAAACyAAAArgAAALEAAAAMAAgABgAAALQAAAABAAAAKwAAALIAAACUAAAAswAAAI4ABQANAAAAtwAA" ++
        "ANIAAAC0AAAA+QACAJcAAAD4AAIAlwAAAPUABwANAAAA0wAAANIAAACPAAAAtwAAAJYAAAD3AAMAvwAAAAAAAAD6AAQAjQAAAL4A" ++
        "AADCAAAA+AACAL4AAABPAAkADQAAAMEAAADTAAAA0wAAAAIAAAABAAAAAAAAAAMAAAD5AAIAvwAAAPgAAgDCAAAA+QACAL8AAAD4" ++
        "AAIAvwAAAPUABwANAAAA1AAAAMEAAAC+AAAA0wAAAMIAAAA+AAMAuQAAANQAAAD9AAEAOAABAA==",
);

pub const shadow_instanced = decodeSpirv(
    "AwIjBwAAAQALAA0AtQIAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ACwAEAAAABAAA" ++
        "AG1haW4AAAAAIAEAACoBAAArAQAARAEAAGMBAABrAQAAEAADAAQAAAAHAAAARwADACABAAAOAAAARwAEACABAAAeAAAABQAAAEcA" ++
        "BAAqAQAAHgAAAAAAAABHAAMAKwEAAA4AAABHAAQAKwEAAB4AAAABAAAARwADAEQBAAAOAAAARwAEAEQBAAAeAAAABAAAAEcAAwBj" ++
        "AQAADgAAAEcABABjAQAAHgAAAAMAAABHAAQAawEAAB4AAAAAAAAARwADAGwBAAACAAAASAAFAGwBAAAAAAAAIwAAAAAAAABIAAUA" ++
        "bAEAAAEAAAAjAAAACAAAAEgABQBsAQAAAgAAACMAAAAQAAAAEwACAAIAAAAhAAMAAwAAAAIAAAAWAAMABgAAACAAAAAXAAQAEQAA" ++
        "AAYAAAACAAAAFwAEACMAAAAGAAAABAAAACsABAAGAAAAQwAAAAAAgD8rAAQABgAAAEQAAACHiY4+KwAEAAYAAABFAAAAGOtrPisA" ++
        "BAAGAAAARgAAABb3nz0VAAQAXwAAACAAAAAAAAAAKwAEAF8AAABgAAAAAQAAACsABAAGAAAAaAAAAAAAAAArAAQAXwAAAGsAAAAA" ++
        "AAAAKwAEAAYAAAB7AAAAAAAAPysABAAGAAAAwwAAAAAAgD4VAAQAywAAACAAAAABAAAAKwAEAMsAAADOAAAAAAAAACsABADLAAAA" ++
        "1QAAAAQAAAAUAAIA1gAAACsABADLAAAA9QAAAAEAAAAsAAUAEQAAAA0BAABoAAAAaAAAACAABAAfAQAAAQAAACMAAAA7AAQAHwEA" ++
        "ACABAAABAAAAKwAEAF8AAAAhAQAAAwAAACAABAAiAQAAAQAAAAYAAAAgAAQAKQEAAAEAAAARAAAAOwAEACkBAAAqAQAAAQAAADsA" ++
        "BAAfAQAAKwEAAAEAAAArAAQAXwAAADEBAAACAAAAOwAEAB8BAABEAQAAAQAAADsABAAfAQAAYwEAAAEAAAAgAAQAagEAAAMAAAAj" ++
        "AAAAOwAEAGoBAABrAQAAAwAAAB4ABQBsAQAAEQAAABEAAAAGAAAAIAAEAG0BAAAJAAAAbAEAADsABABtAQAAbgEAAAkAAAArAAQA" ++
        "ywAAAG8BAAACAAAAIAAEAHABAAAJAAAABgAAACwABQARAAAArwIAAHsAAAB7AAAAKwAEAAYAAACwAgAAAADAvysABAAGAAAAsQIA" ++
        "AAAAwD8rAAQABgAAALICAAAAAAA+KwAEAAYAAACzAgAA8wS1PysABAAGAAAAtAIAAJlsoD82AAUAAgAAAAQAAAAAAAAAAwAAAPgA" ++
        "AgAFAAAAQQAFACIBAAAjAQAAIAEAACEBAAA9AAQABgAAACQBAAAjAQAAugAFANYAAAAlAQAAJAEAAHsAAAD3AAMAKAEAAAAAAAD6" ++
        "AAQAJQEAACcBAAA2AQAA+AACACcBAAA9AAQAEQAAAC0BAAAqAQAAPQAEACMAAAAvAQAAKwEAAEEABQAiAQAAMgEAACABAAAxAQAA" ++
        "PQAEAAYAAAAzAQAAMgEAAE8ABwARAAAAggEAAC8BAAAvAQAAAAAAAAEAAABPAAcAEQAAAIQBAAAvAQAALwEAAAIAAAADAAAAjgAF" ++
        "ABEAAACFAQAAhAEAAHsAAACBAAUAEQAAAIYBAACCAQAAhQEAAIMABQARAAAAhwEAAC0BAACGAQAADAAGABEAAACIAQAAAQAAAAQA" ++
        "AACHAQAAUAAFABEAAACNAQAAMwEAADMBAACDAAUAEQAAAI4BAACFAQAAjQEAAIMABQARAAAAjwEAAIgBAACOAQAADAAHABEAAACR" ++
        "AQAAAQAAACgAAACPAQAADQEAAAwABgAGAAAAkgEAAAEAAABCAAAAkQEAAFEABQAGAAAAlAEAAI8BAAAAAAAAUQAFAAYAAACWAQAA" ++
        "jwEAAAEAAAAMAAcABgAAAJcBAAABAAAAKAAAAJQBAACWAQAADAAHAAYAAACYAQAAAQAAACUAAACXAQAAaAAAAIEABQAGAAAAmQEA" ++
        "AJIBAACYAQAAgwAFAAYAAACbAQAAmQEAADMBAACDAAUABgAAAJ0BAAB7AAAAmwEAAAwACAAGAAAAngEAAAEAAAArAAAAnQEAAGgA" ++
        "AABDAAAAgwAFAAYAAAA1AQAAQwAAAJ4BAAD5AAIAKAEAAPgAAgA2AQAA+QACACgBAAD4AAIAKAEAAPUABwAGAAAAqAIAADUBAAAn" ++
        "AQAAQwAAADYBAAC8AAUA1gAAADkBAACoAgAAaAAAAPcAAwA7AQAAAAAAAPoABAA5AQAAOgEAADsBAAD4AAIAOgEAAPwAAQD4AAIA" ++
        "OwEAAEEABQAiAQAAPgEAACABAABgAAAAPQAEAAYAAAA/AQAAPgEAALoABQDWAAAAQAEAAD8BAABoAAAA9wADAEMBAAAAAAAA+gAE" ++
        "AEABAABCAQAAWAEAAPgAAgBCAQAAPQAEACMAAABFAQAARAEAAE8ABwARAAAARgEAAEUBAABFAQAAAAAAAAEAAABPAAcAEQAAAEgB" ++
        "AABFAQAARQEAAAIAAAADAAAAgQAFABEAAABJAQAARgEAAEgBAACFAAUABgAAAEwBAAA/AQAAewAAAD0ABAARAAAAUgEAACoBAABB" ++
        "AAUAIgEAAFUBAAAgAQAAawAAAD0ABAAGAAAAVgEAAFUBAACBAAUAEQAAALQBAABGAQAASQEAAI4ABQARAAAAtQEAALQBAAB7AAAA" ++
        "gwAFABEAAAC4AQAASQEAAEYBAACOAAUAEQAAALkBAAC4AQAAewAAAIMABQARAAAAvAEAAFIBAAC1AQAAUQAFAAYAAAC+AQAAvAEA" ++
        "AAEAAABRAAUABgAAAMABAAC5AQAAAQAAAIMABQAGAAAAwQEAAL4BAADAAQAAgQAFAAYAAADGAQAAvgEAAMABAACFAAUABgAAAMgB" ++
        "AAA/AQAAsAIAAAwACAAGAAAAywEAAAEAAAArAAAAyAEAAMEBAADGAQAAhQAFAAYAAADNAQAAPwEAALECAAAMAAgABgAAANABAAAB" ++
        "AAAAKwAAAM0BAADBAQAAxgEAAIMABQAGAAAA0wEAANABAADLAQAAhQAFAAYAAADUAQAA0wEAAMMAAACFAAUABgAAANcBAADTAQAA" ++
        "sgIAAIEABQAGAAAA2AEAAMsBAADXAQAA+QACANkBAAD4AAIA2QEAAPUABwAGAAAArQIAANgBAABCAQAA8gEAAN0BAAD1AAcABgAA" ++
        "AKoCAABoAAAAQgEAAO8BAADdAQAA9QAHAMsAAACpAgAAzgAAAEIBAAD1AQAA3QEAALEABQDWAAAA3AEAAKkCAADVAAAA9gAEAPYB" ++
        "AADdAQAAAAAAAPoABADcAQAA3QEAAPYBAAD4AAIA3QEAAIMABQAGAAAA4QEAAL4BAACtAgAAUQAFAAYAAADjAQAAvAEAAAAAAACD" ++
        "AAUABgAAAAICAADAAQAAVgEAAAwABgAGAAAABAIAAAEAAAAEAAAA4QEAAIMABQAGAAAABQIAAAICAAAEAgAADAAHAAYAAAAGAgAA" ++
        "AQAAACUAAAAFAgAAaAAAAFEABQAGAAAACAIAALkBAAAAAAAAgwAFAAYAAAAKAgAACAIAAFYBAACFAAUABgAAAA0CAABWAQAAVgEA" ++
        "AIUABQAGAAAAEAIAAAYCAAAGAgAAgwAFAAYAAAARAgAADQIAABACAAAMAAcABgAAABICAAABAAAAKAAAAGgAAAARAgAADAAGAAYA" ++
        "AAATAgAAAQAAAB8AAAASAgAAgQAFAAYAAAAUAgAACgIAABMCAACDAAUABgAAABcCAADjAQAAFAIAAIgABQAGAAAAGQIAALMCAAA/" ++
        "AQAAhQAFAAYAAAAaAgAAFwIAABkCAAAMAAYABgAAADICAAABAAAABgAAABoCAAAMAAYABgAAADQCAAABAAAABAAAABoCAACFAAUA" ++
        "BgAAADYCAABGAAAANAIAAIUABQAGAAAAOAIAADYCAAA0AgAAgQAFAAYAAAA5AgAARQAAADgCAACFAAUABgAAADsCAAA5AgAANAIA" ++
        "AIEABQAGAAAAPAIAAEQAAAA7AgAAhQAFAAYAAAA+AgAAPAIAADQCAACBAAUABgAAAD8CAABDAAAAPgIAAIUABQAGAAAAQgIAAD8C" ++
        "AAA/AgAAhQAFAAYAAABHAgAAQgIAAEICAACIAAUABgAAAEgCAAAyAgAARwIAAIMABQAGAAAASQIAADICAABIAgAAgQAFAAYAAAAe" ++
        "AgAA4wEAABQCAACFAAUABgAAACECAAAeAgAAGQIAAAwABgAGAAAAUAIAAAEAAAAGAAAAIQIAAAwABgAGAAAAUgIAAAEAAAAEAAAA" ++
        "IQIAAIUABQAGAAAAVAIAAEYAAABSAgAAhQAFAAYAAABWAgAAVAIAAFICAACBAAUABgAAAFcCAABFAAAAVgIAAIUABQAGAAAAWQIA" ++
        "AFcCAABSAgAAgQAFAAYAAABaAgAARAAAAFkCAACFAAUABgAAAFwCAABaAgAAUgIAAIEABQAGAAAAXQIAAEMAAABcAgAAhQAFAAYA" ++
        "AABgAgAAXQIAAF0CAACFAAUABgAAAGUCAABgAgAAYAIAAIgABQAGAAAAZgIAAFACAABlAgAAgwAFAAYAAABnAgAAUAIAAGYCAABQ" ++
        "AAUAEQAAACMCAABJAgAAZwIAAI4ABQARAAAAJAIAACMCAAB7AAAAgQAFABEAAAAmAgAArwIAACQCAABRAAUABgAAACgCAAAmAgAA" ++
        "AQAAAFEABQAGAAAAKgIAACYCAAAAAAAAgwAFAAYAAAArAgAAKAIAACoCAACFAAUABgAAAGwCAACtAgAArQIAAH8ABAAGAAAAbQIA" ++
        "AGwCAACFAAUABgAAAHECAAA/AQAATAEAAIgABQAGAAAAcgIAAG0CAABxAgAADAAGAAYAAABzAgAAAQAAABsAAAByAgAAhQAFAAYA" ++
        "AAB1AgAAPwEAALQCAACIAAUABgAAAHYCAABzAgAAdQIAAIUABQAGAAAA6wEAACsCAAB2AgAAhQAFAAYAAADtAQAA6wEAANQBAACB" ++
        "AAUABgAAAO8BAACqAgAA7QEAAIEABQAGAAAA8gEAAK0CAADUAQAAgAAFAMsAAAD1AQAAqQIAAPUAAAD5AAIA2QEAAPgAAgD2AQAA" ++
        "+QACAEMBAAD4AAIAWAEAAD0ABAARAAAAWgEAACoBAAA9AAQAIwAAAFwBAABEAQAAQQAFACIBAABeAQAAIAEAAGsAAAA9AAQABgAA" ++
        "AF8BAABeAQAATwAHABEAAAB9AgAAXAEAAFwBAAAAAAAAAQAAAE8ABwARAAAAfwIAAFwBAABcAQAAAgAAAAMAAACOAAUAEQAAAIAC" ++
        "AAB/AgAAewAAAIEABQARAAAAgQIAAH0CAACAAgAAgwAFABEAAACCAgAAWgEAAIECAAAMAAYAEQAAAIMCAAABAAAABAAAAIICAABQ" ++
        "AAUAEQAAAIgCAABfAQAAXwEAAIMABQARAAAAiQIAAIACAACIAgAAgwAFABEAAACKAgAAgwIAAIkCAAAMAAcAEQAAAIwCAAABAAAA" ++
        "KAAAAIoCAAANAQAADAAGAAYAAACNAgAAAQAAAEIAAACMAgAAUQAFAAYAAACPAgAAigIAAAAAAABRAAUABgAAAJECAACKAgAAAQAA" ++
        "AAwABwAGAAAAkgIAAAEAAAAoAAAAjwIAAJECAAAMAAcABgAAAJMCAAABAAAAJQAAAJICAABoAAAAgQAFAAYAAACUAgAAjQIAAJMC" ++
        "AACDAAUABgAAAJYCAACUAgAAXwEAAIMABQAGAAAAmAIAAHsAAACWAgAADAAIAAYAAACZAgAAAQAAACsAAACYAgAAaAAAAEMAAAD5" ++
        "AAIAQwEAAPgAAgBDAQAA9QAHAAYAAACrAgAAqgIAAPYBAACZAgAAWAEAAD0ABAAjAAAAZAEAAGMBAACOAAUAIwAAAGYBAABkAQAA" ++
        "qwIAAI4ABQAjAAAAaQEAAGYBAACoAgAAQQAFAHABAABxAQAAbgEAAG8BAAA9AAQABgAAAHIBAABxAQAAugAFANYAAABzAQAAcgEA" ++
        "AHsAAAD3AAMAdgEAAAAAAAD6AAQAcwEAAHUBAAB5AQAA+AACAHUBAABPAAkAIwAAAHgBAABpAQAAaQEAAAIAAAABAAAAAAAAAAMA" ++
        "AAD5AAIAdgEAAPgAAgB5AQAA+QACAHYBAAD4AAIAdgEAAPUABwAjAAAArAIAAHgBAAB1AQAAaQEAAHkBAAA+AAMAawEAAKwCAAD9" ++
        "AAEAOAABAA==",
);

pub const blur_horizontal = decodeSpirv("AwIjBwAAAQALAA0AXAAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ACAAEAAAABAAAAG1haW4AAAAADQAAABQAAABQAAAAEAADAAQAAAAHAAAARwAEAA0AAAAeAAAAAAAAAEcAAwAUAAAADgAAAEcABAAUAAAAHgAAAAUAAABHAAMALQAAAAIAAABIAAUALQAAAAAAAAAjAAAAAAAAAEgABQAtAAAAAQAAACMAAAAIAAAASAAFAC0AAAACAAAAIwAAABAAAABHAAQAQAAAACEAAAAAAAAARwAEAEAAAAAiAAAAAAAAAEcABABQAAAAHgAAAAAAAAATAAIAAgAAACEAAwADAAAAAgAAABUABAAGAAAAIAAAAAEAAAAXAAQABwAAAAYAAAACAAAAFgADAAoAAAAgAAAAFwAEAAsAAAAKAAAAAgAAACAABAAMAAAAAQAAAAsAAAA7AAQADAAAAA0AAAABAAAAFwAEABIAAAAKAAAABAAAACAABAATAAAAAQAAABIAAAA7AAQAEwAAABQAAAABAAAAFQAEABUAAAAgAAAAAAAAACsABAAVAAAAFgAAAAAAAAAgAAQAFwAAAAEAAAAKAAAAKwAEAAoAAAAdAAAAAAAAACwABwASAAAAHgAAAB0AAAAdAAAAHQAAAB0AAAArAAQABgAAACAAAAAAAAAAHgAFAC0AAAALAAAACwAAAAoAAAAgAAQALgAAAAkAAAAtAAAAOwAEAC4AAAAvAAAACQAAACsABAAGAAAAMAAAAAEAAAAgAAQAMQAAAAkAAAAKAAAAFAACADsAAAAZAAkAPQAAAAoAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAbAAMAPgAAAD0AAAAgAAQAPwAAAAAAAAA+AAAAOwAEAD8AAABAAAAAAAAAACAABABPAAAAAwAAABIAAAA7AAQATwAAAFAAAAADAAAANgAFAAIAAAAEAAAAAAAAAAMAAAD4AAIABQAAAD0ABAALAAAADgAAAA0AAABuAAQABwAAAA8AAAAOAAAAQQAFABcAAAAYAAAAFAAAABYAAAA9AAQACgAAABkAAAAYAAAAbgAEAAYAAAAaAAAAGQAAAFEABQAGAAAAIwAAAA8AAAAAAAAAggAFAAYAAAAlAAAAIwAAABoAAAAMAAcABgAAACYAAAABAAAAKgAAACAAAAAlAAAA+QACACcAAAD4AAIAJwAAAPUABwAGAAAAWwAAACAAAAAFAAAATAAAACgAAAD1AAcAEgAAAFoAAAAeAAAABQAAAEoAAAAoAAAA9QAHAAYAAABZAAAAJgAAAAUAAABOAAAAKAAAAEEABgAxAAAAMgAAAC8AAAAwAAAAFgAAAD0ABAAKAAAAMwAAADIAAABuAAQABgAAADQAAAAzAAAAggAFAAYAAAA1AAAANAAAADAAAACAAAUABgAAADkAAAAjAAAAGgAAAAwABwAGAAAAOgAAAAEAAAAnAAAANQAAADkAAACzAAUAOwAAADwAAABZAAAAOgAAAPYABAApAAAAKAAAAAAAAAD6AAQAPAAAACgAAAApAAAA+AACACgAAAA9AAQAPgAAAEEAAABAAAAAUQAFAAYAAABFAAAADwAAAAEAAABQAAUABwAAAEYAAABZAAAARQAAAGQABAA9AAAARwAAAEEAAABfAAcAEgAAAEgAAABHAAAARgAAAAIAAAAgAAAAgQAFABIAAABKAAAAWgAAAEgAAACAAAUABgAAAEwAAABbAAAAMAAAAIAABQAGAAAATgAAAFkAAAAwAAAA+QACACcAAAD4AAIAKQAAAG8ABAAKAAAAUwAAAFsAAABQAAcAEgAAAFQAAABTAAAAUwAAAFMAAABTAAAAiAAFABIAAABVAAAAWgAAAFQAAAA+AAMAUAAAAFUAAAD9AAEAOAABAA==");

pub const blur_vertical = decodeSpirv("AwIjBwAAAQALAA0AkAAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ACQAEAAAABAAAAG1haW4AAAAADQAAABQAAABdAAAAhgAAABAAAwAEAAAABwAAAEcABAANAAAAHgAAAAAAAABHAAMAFAAAAA4AAABHAAQAFAAAAB4AAAAFAAAARwADAC4AAAACAAAASAAFAC4AAAAAAAAAIwAAAAAAAABIAAUALgAAAAEAAAAjAAAACAAAAEgABQAuAAAAAgAAACMAAAAQAAAARwAEAEEAAAAhAAAAAAAAAEcABABBAAAAIgAAAAAAAABHAAMAXQAAAA4AAABHAAQAXQAAAB4AAAAEAAAARwAEAIYAAAAeAAAAAAAAABMAAgACAAAAIQADAAMAAAACAAAAFQAEAAYAAAAgAAAAAQAAABcABAAHAAAABgAAAAIAAAAWAAMACgAAACAAAAAXAAQACwAAAAoAAAACAAAAIAAEAAwAAAABAAAACwAAADsABAAMAAAADQAAAAEAAAAXAAQAEgAAAAoAAAAEAAAAIAAEABMAAAABAAAAEgAAADsABAATAAAAFAAAAAEAAAAVAAQAFQAAACAAAAAAAAAAKwAEABUAAAAWAAAAAAAAACAABAAXAAAAAQAAAAoAAAArAAQACgAAAB0AAAAAAAAALAAHABIAAAAeAAAAHQAAAB0AAAAdAAAAHQAAACsABAAGAAAAIAAAAAAAAAArAAQAFQAAACIAAAABAAAAHgAFAC4AAAALAAAACwAAAAoAAAAgAAQALwAAAAkAAAAuAAAAOwAEAC8AAAAwAAAACQAAACsABAAGAAAAMQAAAAEAAAAgAAQAMgAAAAkAAAAKAAAAFAACADwAAAAZAAkAPgAAAAoAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAbAAMAPwAAAD4AAAAgAAQAQAAAAAAAAAA/AAAAOwAEAEAAAABBAAAAAAAAADsABAATAAAAXQAAAAEAAAArAAQACgAAAHIAAAAAAAA/KwAEAAoAAAB4AAAAAACAPysABAAGAAAAfQAAAAIAAAAgAAQAhQAAAAMAAAASAAAAOwAEAIUAAACGAAAAAwAAADYABQACAAAABAAAAAAAAAADAAAA+AACAAUAAAA9AAQACwAAAA4AAAANAAAAbgAEAAcAAAAPAAAADgAAAEEABQAXAAAAGAAAABQAAAAWAAAAPQAEAAoAAAAZAAAAGAAAAG4ABAAGAAAAGgAAABkAAABRAAUABgAAACQAAAAPAAAAAQAAAIIABQAGAAAAJgAAACQAAAAaAAAADAAHAAYAAAAnAAAAAQAAACoAAAAgAAAAJgAAAPkAAgAoAAAA+AACACgAAAD1AAcABgAAAI0AAAAgAAAABQAAAEwAAAApAAAA9QAHABIAAACMAAAAHgAAAAUAAABKAAAAKQAAAPUABwAGAAAAiwAAACcAAAAFAAAATgAAACkAAABBAAYAMgAAADMAAAAwAAAAMQAAACIAAAA9AAQACgAAADQAAAAzAAAAbgAEAAYAAAA1AAAANAAAAIIABQAGAAAANgAAADUAAAAxAAAAgAAFAAYAAAA6AAAAJAAAABoAAAAMAAcABgAAADsAAAABAAAAJwAAADYAAAA6AAAAswAFADwAAAA9AAAAiwAAADsAAAD2AAQAKgAAACkAAAAAAAAA+gAEAD0AAAApAAAAKgAAAPgAAgApAAAAPQAEAD8AAABCAAAAQQAAAFEABQAGAAAARAAAAA8AAAAAAAAAUAAFAAcAAABGAAAARAAAAIsAAABkAAQAPgAAAEcAAABCAAAAXwAHABIAAABIAAAARwAAAEYAAAACAAAAIAAAAIEABQASAAAASgAAAIwAAABIAAAAgAAFAAYAAABMAAAAjQAAADEAAACAAAUABgAAAE4AAACLAAAAMQAAAPkAAgAoAAAA+AACACoAAABvAAQACgAAAFIAAACNAAAAUAAHABIAAABTAAAAUgAAAFIAAABSAAAAUgAAAIgABQASAAAAVAAAAIwAAABTAAAAQQAFABcAAABVAAAAFAAAACIAAAA9AAQACgAAAFYAAABVAAAAugAFADwAAABXAAAAVgAAAB0AAAD3AAMAWQAAAAAAAAD6AAQAVwAAAFgAAABZAAAA+AACAFgAAAA9AAQAEgAAAF4AAABdAAAATwAHAAsAAABfAAAAXgAAAF4AAAAAAAAAAQAAAFAABQALAAAAYgAAAFYAAABWAAAAgQAFAAsAAABjAAAAXwAAAGIAAABPAAcACwAAAGcAAABeAAAAXgAAAAIAAAADAAAAgQAFAAsAAABoAAAAXwAAAGcAAACDAAUACwAAAGwAAABoAAAAYgAAAAwACAALAAAAbQAAAAEAAAArAAAADgAAAGMAAABsAAAAgQAFAAoAAABzAAAAVgAAAHIAAAAMAAcACgAAAHYAAAABAAAAQwAAAA4AAABtAAAAgwAFAAoAAAB3AAAAcwAAAHYAAAAMAAgACgAAAHkAAAABAAAAKwAAAHcAAAAdAAAAeAAAAI4ABQASAAAAfAAAAFQAAAB5AAAA+QACAFkAAAD4AAIAWQAAAPUABwASAAAAjgAAAFQAAAAqAAAAfAAAAFgAAABBAAUAMgAAAH4AAAAwAAAAfQAAAD0ABAAKAAAAfwAAAH4AAAC6AAUAPAAAAIAAAAB/AAAAcgAAAPcAAwCCAAAAAAAAAPoABACAAAAAgQAAAIIAAAD4AAIAgQAAAE8ACQASAAAAhAAAAI4AAACOAAAAAgAAAAEAAAAAAAAAAwAAAPkAAgCCAAAA+AACAIIAAAD1AAcAEgAAAI8AAACOAAAAWQAAAIQAAACBAAAAPgADAIYAAACPAAAA/QABADgAAQA=");

pub const blur_vertical_pure = decodeSpirv("AwIjBwAAAQALAA0AXAAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ACAAEAAAABAAAAG1haW4AAAAADQAAABQAAABQAAAAEAADAAQAAAAHAAAARwAEAA0AAAAeAAAAAAAAAEcAAwAUAAAADgAAAEcABAAUAAAAHgAAAAUAAABHAAMALgAAAAIAAABIAAUALgAAAAAAAAAjAAAAAAAAAEgABQAuAAAAAQAAACMAAAAIAAAASAAFAC4AAAACAAAAIwAAABAAAABHAAQAQQAAACEAAAAAAAAARwAEAEEAAAAiAAAAAAAAAEcABABQAAAAHgAAAAAAAAATAAIAAgAAACEAAwADAAAAAgAAABUABAAGAAAAIAAAAAEAAAAXAAQABwAAAAYAAAACAAAAFgADAAoAAAAgAAAAFwAEAAsAAAAKAAAAAgAAACAABAAMAAAAAQAAAAsAAAA7AAQADAAAAA0AAAABAAAAFwAEABIAAAAKAAAABAAAACAABAATAAAAAQAAABIAAAA7AAQAEwAAABQAAAABAAAAFQAEABUAAAAgAAAAAAAAACsABAAVAAAAFgAAAAAAAAAgAAQAFwAAAAEAAAAKAAAAKwAEAAoAAAAdAAAAAAAAACwABwASAAAAHgAAAB0AAAAdAAAAHQAAAB0AAAArAAQABgAAACAAAAAAAAAAKwAEABUAAAAiAAAAAQAAAB4ABQAuAAAACwAAAAsAAAAKAAAAIAAEAC8AAAAJAAAALgAAADsABAAvAAAAMAAAAAkAAAArAAQABgAAADEAAAABAAAAIAAEADIAAAAJAAAACgAAABQAAgA8AAAAGQAJAD4AAAAKAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAGwADAD8AAAA+AAAAIAAEAEAAAAAAAAAAPwAAADsABABAAAAAQQAAAAAAAAAgAAQATwAAAAMAAAASAAAAOwAEAE8AAABQAAAAAwAAADYABQACAAAABAAAAAAAAAADAAAA+AACAAUAAAA9AAQACwAAAA4AAAANAAAAbgAEAAcAAAAPAAAADgAAAEEABQAXAAAAGAAAABQAAAAWAAAAPQAEAAoAAAAZAAAAGAAAAG4ABAAGAAAAGgAAABkAAABRAAUABgAAACQAAAAPAAAAAQAAAIIABQAGAAAAJgAAACQAAAAaAAAADAAHAAYAAAAnAAAAAQAAACoAAAAgAAAAJgAAAPkAAgAoAAAA+AACACgAAAD1AAcABgAAAFsAAAAgAAAABQAAAEwAAAApAAAA9QAHABIAAABaAAAAHgAAAAUAAABKAAAAKQAAAPUABwAGAAAAWQAAACcAAAAFAAAATgAAACkAAABBAAYAMgAAADMAAAAwAAAAMQAAACIAAAA9AAQACgAAADQAAAAzAAAAbgAEAAYAAAA1AAAANAAAAIIABQAGAAAANgAAADUAAAAxAAAAgAAFAAYAAAA6AAAAJAAAABoAAAAMAAcABgAAADsAAAABAAAAJwAAADYAAAA6AAAAswAFADwAAAA9AAAAWQAAADsAAAD2AAQAKgAAACkAAAAAAAAA+gAEAD0AAAApAAAAKgAAAPgAAgApAAAAPQAEAD8AAABCAAAAQQAAAFEABQAGAAAARAAAAA8AAAAAAAAAUAAFAAcAAABGAAAARAAAAFkAAABkAAQAPgAAAEcAAABCAAAAXwAHABIAAABIAAAARwAAAEYAAAACAAAAIAAAAIEABQASAAAASgAAAFoAAABIAAAAgAAFAAYAAABMAAAAWwAAADEAAACAAAUABgAAAE4AAABZAAAAMQAAAPkAAgAoAAAA+AACACoAAABvAAQACgAAAFMAAABbAAAAUAAHABIAAABUAAAAUwAAAFMAAABTAAAAUwAAAIgABQASAAAAVQAAAFoAAABUAAAAPgADAFAAAABVAAAA/QABADgAAQA=");

pub const blur_horizontal_paired = decodeSpirv("AwIjBwAAAQALAA0ArQAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ACAAEAAAABAAAAG1haW4AAAAADQAAABQAAACaAAAAEAADAAQAAAAHAAAARwAEAA0AAAAeAAAAAAAAAEcAAwAUAAAADgAAAEcABAAUAAAAHgAAAAUAAABHAAMAIgAAAAIAAABIAAUAIgAAAAAAAAAjAAAAAAAAAEgABQAiAAAAAQAAACMAAAAIAAAASAAFACIAAAACAAAAIwAAABAAAABHAAQAPwAAACEAAAAAAAAARwAEAD8AAAAiAAAAAAAAAEcABACaAAAAHgAAAAAAAAATAAIAAgAAACEAAwADAAAAAgAAABUABAAGAAAAIAAAAAEAAAAXAAQABwAAAAYAAAACAAAAFgADAAoAAAAgAAAAFwAEAAsAAAAKAAAAAgAAACAABAAMAAAAAQAAAAsAAAA7AAQADAAAAA0AAAABAAAAFwAEABIAAAAKAAAABAAAACAABAATAAAAAQAAABIAAAA7AAQAEwAAABQAAAABAAAAFQAEABUAAAAgAAAAAAAAACsABAAVAAAAFgAAAAAAAAAgAAQAFwAAAAEAAAAKAAAAHgAFACIAAAALAAAACwAAAAoAAAAgAAQAIwAAAAkAAAAiAAAAOwAEACMAAAAkAAAACQAAACsABAAGAAAAJQAAAAEAAAAgAAQAJgAAAAkAAAAKAAAAKwAEAAoAAAAzAAAAAAAAPywABQALAAAANAAAADMAAAAzAAAAIAAEADYAAAAJAAAACwAAABkACQA8AAAACgAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAABsAAwA9AAAAPAAAACAABAA+AAAAAAAAAD0AAAA7AAQAPgAAAD8AAAAAAAAAKwAEAAYAAABCAAAAAAAAABQAAgBNAAAAKwAEAAoAAABUAAAAAAAAQCsABAAKAAAAWgAAAAAAAAArAAQABgAAAG4AAAACAAAAIAAEAJkAAAADAAAAEgAAADsABACZAAAAmgAAAAMAAAA2AAUAAgAAAAQAAAAAAAAAAwAAAPgAAgAFAAAAPQAEAAsAAAAOAAAADQAAAG4ABAAHAAAADwAAAA4AAABBAAUAFwAAABgAAAAUAAAAFgAAAD0ABAAKAAAAGQAAABgAAABuAAQABgAAABoAAAAZAAAAUQAFAAYAAAAeAAAADwAAAAAAAAAMAAcABgAAAB8AAAABAAAAJwAAABoAAAAeAAAAQQAGACYAAAAnAAAAJAAAACUAAAAWAAAAPQAEAAoAAAAoAAAAJwAAAG4ABAAGAAAAKQAAACgAAACCAAUABgAAACoAAAApAAAAJQAAAIIABQAGAAAALQAAACoAAAAeAAAADAAHAAYAAAAuAAAAAQAAACcAAAAaAAAALQAAAG8ABAALAAAAMgAAAA8AAACBAAUACwAAADUAAAAyAAAANAAAAEEABQA2AAAANwAAACQAAAAlAAAAPQAEAAsAAAA4AAAANwAAAIgABQALAAAAOQAAADUAAAA4AAAAPQAEAD0AAABAAAAAPwAAAGQABAA8AAAAQwAAAEAAAABfAAcAEgAAAEQAAABDAAAADwAAAAIAAABCAAAA+QACAEYAAAD4AAIARgAAAPUABwASAAAAqAAAAEQAAAAFAAAAqwAAAEkAAAD1AAcABgAAAKUAAAAlAAAABQAAAHAAAABJAAAAswAFAE0AAABOAAAApQAAAB8AAAD2AAQASAAAAEkAAAAAAAAA+gAEAE4AAABHAAAASAAAAPgAAgBHAAAAsQAFAE0AAABRAAAApQAAAB8AAAD3AAMAUwAAAAAAAAD6AAQAUQAAAFIAAABkAAAA+AACAFIAAAA9AAQAPQAAAFUAAAA/AAAAbwAEAAoAAABYAAAApQAAAIEABQAKAAAAWQAAAFgAAAAzAAAAUAAFAAsAAABbAAAAWQAAAFoAAACIAAUACwAAAF4AAABbAAAAOAAAAIMABQALAAAAXwAAADkAAABeAAAAVwAFABIAAABgAAAAVQAAAF8AAACOAAUAEgAAAGEAAABgAAAAVAAAAIEABQASAAAAYwAAAKgAAABhAAAA+QACAFMAAAD4AAIAZAAAAD0ABAA9AAAAZQAAAD8AAABQAAUABwAAAGgAAAClAAAAQgAAAIIABQAHAAAAaQAAAA8AAABoAAAAZAAEADwAAABqAAAAZQAAAF8ABwASAAAAawAAAGoAAABpAAAAAgAAAEIAAACBAAUAEgAAAG0AAACoAAAAawAAAPkAAgBTAAAA+AACAFMAAAD1AAcAEgAAAKsAAABjAAAAUgAAAG0AAABkAAAA+QACAEkAAAD4AAIASQAAAIAABQAGAAAAcAAAAKUAAABuAAAA+QACAEYAAAD4AAIASAAAAPkAAgByAAAA+AACAHIAAAD1AAcAEgAAAKcAAACoAAAASAAAAKwAAAB1AAAA9QAHAAYAAACmAAAAJQAAAEgAAACYAAAAdQAAALMABQBNAAAAeQAAAKYAAAAuAAAA9gAEAHQAAAB1AAAAAAAAAPoABAB5AAAAcwAAAHQAAAD4AAIAcwAAALEABQBNAAAAfAAAAKYAAAAuAAAA9wADAH4AAAAAAAAA+gAEAHwAAAB9AAAAjQAAAPgAAgB9AAAAPQAEAD0AAAB/AAAAPwAAAG8ABAAKAAAAggAAAKYAAACBAAUACgAAAIMAAACCAAAAMwAAAFAABQALAAAAhAAAAIMAAABaAAAAiAAFAAsAAACHAAAAhAAAADgAAACBAAUACwAAAIgAAAA5AAAAhwAAAFcABQASAAAAiQAAAH8AAACIAAAAjgAFABIAAACKAAAAiQAAAFQAAACBAAUAEgAAAIwAAACnAAAAigAAAPkAAgB+AAAA+AACAI0AAAA9AAQAPQAAAI4AAAA/AAAAUAAFAAcAAACRAAAApgAAAEIAAACAAAUABwAAAJIAAAAPAAAAkQAAAGQABAA8AAAAkwAAAI4AAABfAAcAEgAAAJQAAACTAAAAkgAAAAIAAABCAAAAgQAFABIAAACWAAAApwAAAJQAAAD5AAIAfgAAAPgAAgB+AAAA9QAHABIAAACsAAAAjAAAAH0AAACWAAAAjQAAAPkAAgB1AAAA+AACAHUAAACAAAUABgAAAJgAAACmAAAAbgAAAPkAAgByAAAA+AACAHQAAACAAAUABgAAAJ0AAAAlAAAAHwAAAIAABQAGAAAAnwAAAJ0AAAAuAAAAbwAEAAoAAACgAAAAnwAAAFAABwASAAAAoQAAAKAAAACgAAAAoAAAAKAAAACIAAUAEgAAAKIAAACnAAAAoQAAAD4AAwCaAAAAogAAAP0AAQA4AAEA");

pub const blur_vertical_paired = decodeSpirv("AwIjBwAAAQALAA0ArgAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ACAAEAAAABAAAAG1haW4AAAAADQAAABQAAACbAAAAEAADAAQAAAAHAAAARwAEAA0AAAAeAAAAAAAAAEcAAwAUAAAADgAAAEcABAAUAAAAHgAAAAUAAABHAAMAIwAAAAIAAABIAAUAIwAAAAAAAAAjAAAAAAAAAEgABQAjAAAAAQAAACMAAAAIAAAASAAFACMAAAACAAAAIwAAABAAAABHAAQAQAAAACEAAAAAAAAARwAEAEAAAAAiAAAAAAAAAEcABACbAAAAHgAAAAAAAAATAAIAAgAAACEAAwADAAAAAgAAABUABAAGAAAAIAAAAAEAAAAXAAQABwAAAAYAAAACAAAAFgADAAoAAAAgAAAAFwAEAAsAAAAKAAAAAgAAACAABAAMAAAAAQAAAAsAAAA7AAQADAAAAA0AAAABAAAAFwAEABIAAAAKAAAABAAAACAABAATAAAAAQAAABIAAAA7AAQAEwAAABQAAAABAAAAFQAEABUAAAAgAAAAAAAAACsABAAVAAAAFgAAAAAAAAAgAAQAFwAAAAEAAAAKAAAAKwAEABUAAAAdAAAAAQAAAB4ABQAjAAAACwAAAAsAAAAKAAAAIAAEACQAAAAJAAAAIwAAADsABAAkAAAAJQAAAAkAAAArAAQABgAAACYAAAABAAAAIAAEACcAAAAJAAAACgAAACsABAAKAAAANAAAAAAAAD8sAAUACwAAADUAAAA0AAAANAAAACAABAA3AAAACQAAAAsAAAAZAAkAPQAAAAoAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAbAAMAPgAAAD0AAAAgAAQAPwAAAAAAAAA+AAAAOwAEAD8AAABAAAAAAAAAACsABAAGAAAAQwAAAAAAAAAUAAIATgAAACsABAAKAAAAVQAAAAAAAEArAAQACgAAAFgAAAAAAAAAKwAEAAYAAABvAAAAAgAAACAABACaAAAAAwAAABIAAAA7AAQAmgAAAJsAAAADAAAANgAFAAIAAAAEAAAAAAAAAAMAAAD4AAIABQAAAD0ABAALAAAADgAAAA0AAABuAAQABwAAAA8AAAAOAAAAQQAFABcAAAAYAAAAFAAAABYAAAA9AAQACgAAABkAAAAYAAAAbgAEAAYAAAAaAAAAGQAAAFEABQAGAAAAHwAAAA8AAAABAAAADAAHAAYAAAAgAAAAAQAAACcAAAAaAAAAHwAAAEEABgAnAAAAKAAAACUAAAAmAAAAHQAAAD0ABAAKAAAAKQAAACgAAABuAAQABgAAACoAAAApAAAAggAFAAYAAAArAAAAKgAAACYAAACCAAUABgAAAC4AAAArAAAAHwAAAAwABwAGAAAALwAAAAEAAAAnAAAAGgAAAC4AAABvAAQACwAAADMAAAAPAAAAgQAFAAsAAAA2AAAAMwAAADUAAABBAAUANwAAADgAAAAlAAAAJgAAAD0ABAALAAAAOQAAADgAAACIAAUACwAAADoAAAA2AAAAOQAAAD0ABAA+AAAAQQAAAEAAAABkAAQAPQAAAEQAAABBAAAAXwAHABIAAABFAAAARAAAAA8AAAACAAAAQwAAAPkAAgBHAAAA+AACAEcAAAD1AAcAEgAAAKkAAABFAAAABQAAAKwAAABKAAAA9QAHAAYAAACmAAAAJgAAAAUAAABxAAAASgAAALMABQBOAAAATwAAAKYAAAAgAAAA9gAEAEkAAABKAAAAAAAAAPoABABPAAAASAAAAEkAAAD4AAIASAAAALEABQBOAAAAUgAAAKYAAAAgAAAA9wADAFQAAAAAAAAA+gAEAFIAAABTAAAAZQAAAPgAAgBTAAAAPQAEAD4AAABWAAAAQAAAAG8ABAAKAAAAWgAAAKYAAACBAAUACgAAAFsAAABaAAAANAAAAFAABQALAAAAXAAAAFgAAABbAAAAiAAFAAsAAABfAAAAXAAAADkAAACDAAUACwAAAGAAAAA6AAAAXwAAAFcABQASAAAAYQAAAFYAAABgAAAAjgAFABIAAABiAAAAYQAAAFUAAACBAAUAEgAAAGQAAACpAAAAYgAAAPkAAgBUAAAA+AACAGUAAAA9AAQAPgAAAGYAAABAAAAAUAAFAAcAAABpAAAAQwAAAKYAAACCAAUABwAAAGoAAAAPAAAAaQAAAGQABAA9AAAAawAAAGYAAABfAAcAEgAAAGwAAABrAAAAagAAAAIAAABDAAAAgQAFABIAAABuAAAAqQAAAGwAAAD5AAIAVAAAAPgAAgBUAAAA9QAHABIAAACsAAAAZAAAAFMAAABuAAAAZQAAAPkAAgBKAAAA+AACAEoAAACAAAUABgAAAHEAAACmAAAAbwAAAPkAAgBHAAAA+AACAEkAAAD5AAIAcwAAAPgAAgBzAAAA9QAHABIAAACoAAAAqQAAAEkAAACtAAAAdgAAAPUABwAGAAAApwAAACYAAABJAAAAmQAAAHYAAACzAAUATgAAAHoAAACnAAAALwAAAPYABAB1AAAAdgAAAAAAAAD6AAQAegAAAHQAAAB1AAAA+AACAHQAAACxAAUATgAAAH0AAACnAAAALwAAAPcAAwB/AAAAAAAAAPoABAB9AAAAfgAAAI4AAAD4AAIAfgAAAD0ABAA+AAAAgAAAAEAAAABvAAQACgAAAIMAAACnAAAAgQAFAAoAAACEAAAAgwAAADQAAABQAAUACwAAAIUAAABYAAAAhAAAAIgABQALAAAAiAAAAIUAAAA5AAAAgQAFAAsAAACJAAAAOgAAAIgAAABXAAUAEgAAAIoAAACAAAAAiQAAAI4ABQASAAAAiwAAAIoAAABVAAAAgQAFABIAAACNAAAAqAAAAIsAAAD5AAIAfwAAAPgAAgCOAAAAPQAEAD4AAACPAAAAQAAAAFAABQAHAAAAkgAAAEMAAACnAAAAgAAFAAcAAACTAAAADwAAAJIAAABkAAQAPQAAAJQAAACPAAAAXwAHABIAAACVAAAAlAAAAJMAAAACAAAAQwAAAIEABQASAAAAlwAAAKgAAACVAAAA+QACAH8AAAD4AAIAfwAAAPUABwASAAAArQAAAI0AAAB+AAAAlwAAAI4AAAD5AAIAdgAAAPgAAgB2AAAAgAAFAAYAAACZAAAApwAAAG8AAAD5AAIAcwAAAPgAAgB1AAAAgAAFAAYAAACeAAAAJgAAACAAAACAAAUABgAAAKAAAACeAAAALwAAAG8ABAAKAAAAoQAAAKAAAABQAAcAEgAAAKIAAAChAAAAoQAAAKEAAAChAAAAiAAFABIAAACjAAAAqAAAAKIAAAA+AAMAmwAAAKMAAAD9AAEAOAABAA==");

fn decodedSize(comptime encoded: []const u8) usize {
    return std.base64.standard.Decoder.calcSizeForSlice(encoded) catch unreachable;
}

fn decodeSpirv(comptime encoded: []const u8) [decodedSize(encoded) / @sizeOf(u32)]u32 {
    @setEvalBranchQuota(10_000);
    const byte_count = decodedSize(encoded);
    comptime std.debug.assert(byte_count % @sizeOf(u32) == 0);
    var bytes: [byte_count]u8 = undefined;
    _ = std.base64.standard.Decoder.decode(&bytes, encoded) catch unreachable;
    var words: [byte_count / @sizeOf(u32)]u32 = undefined;
    for (&words, 0..) |*word, index| {
        word.* = std.mem.readInt(u32, bytes[index * 4 ..][0..4], .little);
    }
    return words;
}
